### ISSUE TITLE
hex_random do not work in 0.6.0pre1

### ISSUE THREAD

**Issue by timesking** [fluent/fluent-plugin-s3#108]
I got a empty string with %{hex_random}

**Comment by repeatedly** [comment]
Because 0.6.0pre1 doesn't have hex_random.

**Comment by timesking** [comment]
Could you organize version with github milestone feature?
That helps me to understand which will added into which version.

**Comment by repeatedly** [comment]
We have changelog so it describes when features are implemeneted.

https://github.com/fluent/fluent-plugin-s3/blob/master/ChangeLog

I'm not familiar with the detail of milestone features.
Milestone fits for hex_random like small enhancement?
I know some big changes are organized by milestone.

**Comment by repeatedly** [comment]
BTW, we should separate commits into feature implementation and document update.
