### ISSUE TITLE
Time-based variables on s3_object_key_format whose granularity is different from time_slice_format

### ISSUE THREAD

**Issue by TakahikoKawasaki** [fluent/fluent-plugin-s3#113]
How can I specify time-based variables on `s3_object_key_format` whose granularity is different from `time_slice_format`? For example, when `time_slice_format` is `%Y%m%d-%H`, how can I create a directory structure like below?

    YYYY/MM/DD/%{time_slice}_%{index}.log.gz

I want to create a directory per year/month/day whatever the value of `time_slice_format` is.

**Comment by repeatedly** [comment]
There are no way for now.
The easist way is implementing your S3 plugin based on `S3Output`.

**Comment by TakahikoKawasaki** [comment]
I actually did it before in a certain project, and now I want to do the same thing in another project. This is just a guess, but I think other people in the world want to do the same thing, too. Has this feature been discussed in fluentd community so far?

**Comment by repeatedly** [comment]
Some elasticsearch users want similar feature > https://github.com/uken/fluent-plugin-elasticsearch/pull/127

**Comment by sonots** [comment]
@TakahikoKawasaki Not tried, but `time_slice_format %Y/%m/%d/%Y%m%d-%H` with `%{time_slice}_%{index}.log.gz` does not work?

**Comment by TakahikoKawasaki** [comment]
@sonots Thank you very much. It worked!
