### ISSUE TITLE
ArgumentError: invalid configuration option `:s3_server_side_encryption'

### ISSUE THREAD

**Issue by diclophis** [fluent/fluent-plugin-s3#114]
Hello, we are getting this error in our `td-agent.log`

    2015-10-21 23:35:28 +0000 [error]: unexpected error error_class=ArgumentError error=#<ArgumentError: invalid configuration option `:s3_server_side_encryption'>

The relevant line of config is...

    <store>
      use_server_side_encryption aes256
    </store>

Any advice / guidance / fixes would be helpful

**Comment by repeatedly** [comment]
It seems use_server_side_encryption is removed accidentially.
Please wait.

**Comment by repeatedly** [comment]
Ah wait. The problem is server_side_encryption is moved from constructor to each operation.

**Comment by repeatedly** [comment]
@diclophis I wrote a patch. Could you test it?

**Comment by diclophis** [comment]
@repeatedly Thanks for the quick update, we will look into the issue here shortly, I am uncertain as to how to install the specific version of the gem via `td-agent-gem install ...` Do you have a guideline for that?

**Comment by repeatedly** [comment]
One idea is downloading https://raw.githubusercontent.com/fluent/fluent-plugin-s3/bb6516221383b60a683b728c9d6c56cdf9b4c3f5/lib/fluent/plugin/out_s3.rb and copy it into exsiting out_s3.rb

**Comment by repeatedly** [comment]
@diclophis How about this? Can we merge the patch?

**Comment by diclophis** [comment]
I think the patch looks good overall, we have actually decided to re-architect our log flow, and will be using this ES plugin: https://github.com/elastic/elasticsearch-cloud-aws to facilitate our S3 storage requirements.

Unfortunately we have no ability to test this plugin because we have removed the necessary configuration from our systems...

**Comment by repeatedly** [comment]
Ah, I see. Thanks for reporting this.
ES-cloud-aws plugin seems interesting.

BTW, I will merge the patch and release new version soon.
