### ISSUE TITLE
dynamic values for path

### ISSUE THREAD

**Issue by ranjeetkgupta** [fluent/fluent-plugin-s3#118]
I am trying to have dynamic values for path based on the tag last name.  

#path log/${tag_parts.last}/

This doesn't seem to work though. It creates the same folder name ("${tag_parts.last}") in S3. Is it not supposed to work with dynamic values ?

**Comment by repeatedly** [comment]
> Is it not supposed to work with dynamic values ?

Yes. See this issue > https://github.com/fluent/fluent-plugin-s3/issues/58
