### ISSUE TITLE
Feature request: want names of new S3 files as they are saved

### ISSUE THREAD

**Issue by lance-edmodo** [fluent/fluent-plugin-s3#128]
For a fully streaming infrastructure it would be very handy to have a new event generated inside Fluentd whenever a new S3 file is created. I would use this to trigger loading this file into our data warehouse as soon as it was created. 

For example, a new directive in the s3 output plugin:

tag s3_file

would send a message to the tag 's3_file' with a 'filename' field that contains the complete s3 path:

{"filename":"s3://bucket/a/b/file-deadbeef.gz"}

The message might also include metadata like time of creation and length of file.

{"filename":"s3://bucket/a/b/file-deadbeef.gz", "timestamp":"2016-01-01 01:01:01", "length": 56737}

**Comment by repeatedly** [comment]
I think S3 Event Notification is useful for this purpose: http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html

**Comment by repeatedly** [comment]
Using AWS features is better than supporting in S3 plugins.
