### ISSUE TITLE
can this plugin store logs in s3 with better path

### ISSUE THREAD

**Issue by holajoyce** [fluent/fluent-plugin-s3#129]
would like to be able to store paths by hourly if possible

**Comment by repeatedly** [comment]
See README: https://github.com/fluent/fluent-plugin-s3#configuration
You can set `time_slice_format %Y%m%d%H` or similar.

**Comment by holajoyce** [comment]
can it create an daily hourly directory, like i would with camus into hdfs?  Thanks

**Comment by repeatedly** [comment]
Try it.
