### ISSUE TITLE
Authentication method

### ISSUE THREAD

**Issue by Nabouk** [fluent/fluent-plugin-s3#130]
Hello, 

I am using the plugin with a third party storage compatible with S3. 

Which authentication method is used with fluent-plugin-s3 ? I am getting errors since my application uses authentication V2. 
Is authentication V2 implemented ? 
Thx

**Comment by repeatedly** [comment]
> Is authentication V2 implemented ? 

We don't touch authentication version via configration so s3 plugin uses Ruby SDK default.
If Ruby SDK v2.x supports v2 authentication, we can also support it.
Could you send a patch if Ruby SDK v2.x with authentication v2 works on your environment?

**Comment by repeatedly** [comment]
No response.
