### ISSUE TITLE
Documented feature acl not supported

### ISSUE THREAD

**Issue by davidhybner** [fluent/fluent-plugin-s3#132]
There are two issues.
First, acl is documented in the Configuration setting, but it doesn't work.  You aren't adding the config_param acl to put_options
```
        put_options[:ssekms_key_id] = @ssekms_key_id if @ssekms_key_id
        put_options[:acl] = @acl if @acl
        @bucket.object(s3path).put(put_options)
```

Second, the documentation is wrong in README.md for acl.  You are using '_' when it should be '-'
Current:
bucket_owner_read
Should be:
bucket-owner-read
See: http://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl

**Comment by repeatedly** [comment]
@okkez Could you check?

**Comment by okkez** [comment]
First, `@acl` is not used in out_s3.rb. We should set `@acl` to `put_options`.
Second, current README.md is wrong. We should replace `_` with `-`.

**Comment by repeatedly** [comment]
Release v0.6.6 including fix. Thanks for the report.
