### ISSUE TITLE
s3 upload time interval

### ISSUE THREAD

**Issue by pankajgrovertt** [fluent/fluent-plugin-s3#136]
how can I control time interval of s3 upload ?

**Comment by repeatedly** [comment]
See this official article: http://docs.fluentd.org/articles/out_s3

**Comment by pankajgrovertt** [comment]
Thanks for the reply. I wanted to confirm if I specify time_slice_format  %Y%m%d , will it create s3 buffer file once in a day ?
I don't want to create file per hour.

**Comment by repeatedly** [comment]
If buffer chunk reached `buffer_chunk_limit`, S3 plugin uploads its chunk to S3.
If you want to avoid it, please set larger value to `buffer_chunk_limit` and `buffer_queue_limit`.

**Comment by pankajgrovertt** [comment]
Thanks a lot !
