### ISSUE TITLE
Experiencing delayed upload to S3 dependent on secure_forward emptying buffers

### ISSUE THREAD

**Issue by jeremydonahue** [fluent/fluent-plugin-s3#137]
Hi here,

We are experiencing some unexplained delays with chunks not being pushed to s3 until _all_ of the secure_forward instances have fully flushed their buffers. 

The image below depicts the behavior we are seeing. The chart on the left is the count of buffer files in the aggregator's out_s3 buffer directory. The chart on the right is the count of buffer files in the secure_forward buffer directory. As you can see the buffer counts begin to increase in both charts at ~6:00 when our data-generating-process starts. Neither log files contain any information hinting at the cause. The aggregator's out_s3 buffers then begin to fill pretty rapidly, and the frequency of chunk uploads to s3 drops dramatically (~450 uploads/hour to ~100/per hour, even though the record count increased exponentially). This condition persists until the secure_forward instances have flushed _all_ of their buffers (seen at ~8:40 in the chart on the right) after which the out_s3 plugin rapidly flushes all of the chunks it was buffering.

Our configs are below. We appreciate any insight you could give into the problem.

Thanks,
Jeremy

Notes: 1) We are using `flush_interval` instead of `time_slice_wait` because we want logs to be delivered to S3 at a regular interval even if the chunks aren't full to ensure timely delivery. 2) The start time of the buffer backup seems to move around a bit (today it started at 3:30), but happens consistently every morning.

![selection_018](https://cloud.githubusercontent.com/assets/14008978/13831061/19e15940-eb8e-11e5-8563-8f0ba777399b.png)

Log generating servers:

```
<match **>
  type                secure_forward
  shared_key          key
  self_hostname       ${hostname}
  send_timeout        60s

  buffer_type         file
  buffer_path         /var/spool/td-agent/forward
  buffer_chunk_limit  16m
  buffer_queue_limit  2048
  flush_interval      10s
  retry_wait          20s
  disable_retry_limit true
  flush_at_shutdown  true

  <server>
    host     listener-01.domain.com
    port     <port1>
    standby  no
  </server>
  <server>
    host     listener-01.domain.com
    port     <port2>
    standby  no
  </server>
  ...
</match>
```

Fluentd listener/secure forward hosts:

```
<match tagname.**>
  type copy

  # Forward to the aggregator instance
  <store>
    type               secure_forward
    shared_key         key
    self_hostname      ${hostname}

    buffer_type         file
    buffer_path         /var/spool/td-agent/listener-24284.forward.tagname
    buffer_chunk_limit  16m
    buffer_queue_limit  2048
    flush_interval      10s
    retry_wait          20s
    max_retry_wait      30s
    disable_retry_limit true
    flush_at_shutdown   true
    secure              false

    <server>
      host     aggregator-01.domain.com
      port     <agg port>
      standby  no
    </server>
  </store>
</match>

#...other match blocks same similar to above

<match **>
  type copy

  # Forward to the aggregator instance
  <store>
    type               secure_forward
    shared_key         key
    self_hostname      ${hostname}

    # File buffering - 16m * 512 = 8g
    buffer_type         file
    buffer_path         /var/spool/td-agent/listener-24284.forward
    buffer_chunk_limit  16m
    buffer_queue_limit  512
    flush_interval      10s
    retry_wait          20s
    max_retry_wait      30s
    disable_retry_limit true
    flush_at_shutdown   true
    secure              false

    <server>
      host     aggregator-01.domain.com
      port     <agg port>
      standby  no
    </server>
  </store>

  # Forward to elasticsearch
  <store>
    type                elasticsearch
    logstash_format     true
    logstash_prefix     logstash
    include_tag_key     true
    tag_key             tag
    type_name           fluentd
    type_key            _type

    buffer_type         file
    buffer_path         /var/spool/td-agent/listener-24284.elasticsearch
    buffer_chunk_limit  16m
    buffer_queue_limit  512
    flush_interval      5s
    retry_wait          15s
    max_retry_wait      30s
    disable_retry_limit true
    flush_at_shutdown   true

    resurrect_after     0  # default is 60
    utc_index           false
  </store>
</match>
```

Aggregator/out_s3 conf. 
Note: This is using the `forest` plugin, but we have the same `<store>` block [via templates] for different dedicated `<match>`'s and those exhibit the same behavior.

```
<match **>
  type     forest
  subtype  copy
  <template>

    # Store in s3
    <store>
      @log_level            debug

      type                  s3
      aws_key_id            key
      aws_sec_key           key
      s3_region             region
      s3_bucket             bucketname
      path                  <path>/${tag}/
      s3_object_key_format  %{path}%{year}/%{month}/%{day}/${tag}.%{time_slice}_%{uuid_flush}.gz
      format                json
      include_tag_key       true
      tag_key               @tag
      include_time_key      true
      time_key              @timestamp
      time_format           %Y-%m-%dT%H:%M:%S%z
      time_slice_format     %Y%m%d%H
      flush_interval        5m
      store_as              gzip
      use_ssl               yes
      num_threads           4

      buffer_type           file
      buffer_path           /var/spool/td-agent/s3/${tag}
      buffer_chunk_limit    32m
      buffer_queue_limit    4098
      retry_wait            1s
      max_retry_wait        5s
      disable_retry_limit   true
    </store>

    # Store in a local file
    <store>
      type               file
      path               <path>/${tag}
      append             true
      time_slice_format  %Y%m%d-%H
      time_format        %Y%m%dT%H%M%S%z
      time_slice_wait    10m
      format             json
      include_tag_key    true
      tag_key            @tag
      include_time_key   true
      time_format        %Y-%m-%dT%H:%M:%S%z
      time_key           @timestamp
      buffer_chunk_limit 32m
    </store>
  </template>
</match>
```

**Comment by repeatedly** [comment]
> As you can see the buffer counts begin to increase in both charts at ~6:00 when our data-generating-process starts

It measn you generate lots of logs since around 6:00 or log volume is same but the number of buffer chunks is growing suddenly?

**Comment by jeremydonahue** [comment]
It means we generate lots of logs at that time.

**Comment by repeatedly** [comment]
How fluentd and machine consume CPUs?

**Comment by jeremydonahue** [comment]
The load increases and peaks at about 7, which isn't super high. It is possible that each fluentd process is using 100% of a core but I would have to record some metrics tonight to get that info. We have 8 secure_forward processes, 1 s3_out aggregator process & 32 cores on the host. Could that cause this problem?

**Comment by repeatedly** [comment]
Currenlty, fluentd uses only 1 core by Ruby's limitation. This will be resolved by multiprocess support since v0.14.
So if your aggregator consumes CPU 100%, uploading files may be delayed.

**Comment by jeremydonahue** [comment]
So the solution is to use multiple aggregators via the multiprocess plugin for out_s3?

**Comment by repeatedly** [comment]
Yes, it is possible solution.

**Comment by kenhys** [comment]
It will be solved by https://github.com/fluent/fluent-plugin-s3/issues/137#issuecomment-198060763
