### ISSUE TITLE
How do time_slice_format and flush_interval affect how many chunks are created in s3?

### ISSUE THREAD

**Issue by pkaeding** [fluent/fluent-plugin-s3#142]
I'm unclear on how `time_slice_format` and `flush_interval` interact.  I had the following two lines:

```
      time_slice_format %Y/%m/%d/%Y-%m-%dT%H:%MZ
      flush_interval 10m
```

I was expecting to see files like:

```
2016/03/30/2016-03-30T20:30Z_0.gz # including entries from [20:30, 20:40)
2016/03/30/2016-03-30T20:40Z_0.gz # including entries from [20:40, 20:50)
...
```

However, I see one file for each minute.  I guess this makes sense, since the docs seem to imply that the `time_slice_format` is not only used to format the time name, but also to decide when to start a new file.  So then, what does `flush_interval` do?  Is there any way for me to have 10-minute chunks?

**Comment by repeatedly** [comment]
> However, I see one file for each minute.

This is by `%M` in `time_slice_format %Y/%m/%d/%Y-%m-%dT%H:%MZ`.

http://docs.fluentd.org/articles/buffer-plugin-overview#time-sliced-plugin-overview

time_slice_format is used for chunk boundary.
In this configuration, files are uploaded within minute interval.
So flush_interval is ignored when you specifies larger time slice than flush_interval.

> Is there any way for me to have 10-minute chunks?

Almost users use `%Y/%m/%d/%H` and `flush_interval 10m` for 10-minute chunks.
But this way doesn't include minute in the filename.

**Comment by pkaeding** [comment]
Okay, thanks. I suppose that will work for me.
