### ISSUE TITLE
No way to set storage_class

### ISSUE THREAD

**Issue by lidocaineus** [fluent/fluent-plugin-s3#143]
There doesn't appear to be a way to set storage classes using the plugin. Right now you can set the reduced redundancy storage class by setting reduced_redundancy, but there's no way to utilize the standard-ia class directly. You could also utilize it with a workaround if you could inject manual headers, but there doesn't appear to be an option for thet either.

**Comment by repeatedly** [comment]
How about using storage_class option? > https://github.com/fluent/fluent-plugin-s3/blob/master/lib/fluent/plugin/out_s3.rb#L95
http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Types/HeadObjectOutput.html#storage_class-instance_method

**Comment by lidocaineus** [comment]
Ah, I'm not use to digging through the source for config parameters :) However that seems to be appropriate. Looks like this can be closed.

**Comment by repeatedly** [comment]
I noticed `storage_class` is not listed in README.
I will add it...

**Comment by repeatedly** [comment]
Added to README
