### ISSUE TITLE
avro format?

### ISSUE THREAD

**Issue by mikeleeme** [fluent/fluent-plugin-s3#153]
Hi there,

Does the S3 plugin support output [Avro](https://avro.apache.org/) format?

Thanks

**Comment by repeatedly** [comment]
fluent-plugin-s3 depends on formatter plugin for formatting record.
I'm not sure avro formatter plugin exist or not.
If not, you need to write formatter plugin.

**Comment by mikeleeme** [comment]
@repeatedly I see, thanks for your tip!

**Comment by dobesv** [comment]
https://github.com/takebayashi/fluent-plugin-avro
