### ISSUE TITLE
Feature Request: Dynamic Path Generated by Tag

### ISSUE THREAD

**Issue by zfoxdev** [fluent/fluent-plugin-s3#162]
It would be nice to have an option in the configuration of this plugin, so that when using a generic `<match **>`, a tag of `my.custom.tag` would be turned into the s3 path `my/custom/tag/`.

This would allow data to be dynamically routed different folders in s3 based on the tag that is provided in the request to fluentd.

**Comment by repeatedly** [comment]
You can realize it via fluent-plugin-forest: https://github.com/tagomoris/fluent-plugin-forest

In v0.14, we will remove forest for this feature.

**Comment by kgf** [comment]
@repeatedly Could you elaborate what you mean by this quote ?

> In v0.14, we will remove forest for this feature.
Thanks
Kevin

**Comment by repeatedly** [comment]
v0.14 new plugin API provides it.
See out_file case: http://www.fluentd.org/blog/fluentd-v0.14.9-has-been-released
