### ISSUE TITLE
Request: optionally read aws key and secret from environment variables

### ISSUE THREAD

**Issue by pydolan** [fluent/fluent-plugin-s3#163]
Check out how [Logstash's s3 plugin does this](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-s3.html#plugins-outputs-s3-access_key_id).  They check the following locations, in this order:

> 1. Static configuration, using access_key_id and secret_access_key params in logstash plugin config
> 2. External credentials file specified by aws_credentials_file
> 3. Environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
> 4. Environment variables AMAZON_ACCESS_KEY_ID and AMAZON_SECRET_ACCESS_KEY
> 5. IAM Instance Profile (available when running inside EC2)

**Comment by repeatedly** [comment]
Fluentd configuration has already supported environment variables access like below.

`aws_key_id "#{ENV['AWS_ACCESS_KEY_ID']}"`

**Comment by pydolan** [comment]
Cool, thanks.
