### ISSUE TITLE
shutdown of s3 plugin seems to crash in fluentd v14.6

### ISSUE THREAD

**Issue by jottos** [fluent/fluent-plugin-s3#166]
We get the following error in logs:

> 2016-10-09 04:43:05 +0000 [trace]: plugin/buffer.rb:165:add_metadata: adding metadata instance=70046040369760 metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1475985600, tag=nil, variables=nil>
> 2016-10-09 04:43:05 +0000 [warn]: fluent/root_agent.rb:277:handle_emits_error: emit transaction failed: error_class=NoMethodError error="undefined mfethod `index' for nil:NilClass" tag="fluent.debug"
>   2016-10-09 04:43:05 +0000 [warn]: fluent/event_router.rb:81:emit: suppressed same stacktrace
> 2016-10-09 04:43:05 +0000 [error]: fluent/engine.rb:167:rescue in block in log_event_loop: failed to emit fluentd's log event tag="fluent.debug" event={"instance"=>70046039242500, "message"=>"closing buffer instance=70\
> 046039242500"} error_class=NoMethodError error="undefined method`index' for nil:NilClass"

Out configs for s3 are:

```
  <store>
    @type forest
    subtype s3
    <template>
      aws_key_id XXX
      aws_sec_key XXX
      s3_bucket apixio-logs
      s3_region us-west-1
      buffer_path /var/log/td-agent/s3/${tag_parts[1..-1]}
      buffer_chunk_limit 64m
      buffer_queue_limit 64
      flush_at_shutdown true
      time_slice_wait 10m
      time_slice_format %Y-%m-%d/%Y-%m-%dT%H
      utc
      path user/logmaster/staging
      s3_object_key_format %{path}/${tag_parts[-1]}/%{time_slice}-%{hostname}-%{index}.json.%{file_extension}
      format json
    </template>
  </store>
```

and

```
<match fluent.**>
  type s3
  aws_key_id XXX
  aws_sec_key  XXX
  s3_bucket apixio-logs
  s3_region us-west-1
  buffer_path "/var/log/td-agent/s3/fluent"
  buffer_chunk_limit 16m
  buffer_queue_limit 64
  flush_at_shutdown true
  time_slice_wait 10m
  time_slice_format %Y-%m-%dT%H
  utc
  path user/logmaster/fluentlogs
  s3_object_key_format "%{path}/%{time_slice}-%{hostname}-%{index}.json.%{file_extension}"
</match>
```

**Comment by repeatedly** [comment]
Could you show me the entire stacktrace?
fluent-plugin-s3 doesn't use `index` method, so the problem seems the outside of s3 plugin.

**Comment by repeatedly** [comment]
And does this happen with latest v0.14.8?

**Comment by jottos** [comment]
this was all that was in the logs, not much of a stack trace, sorry.

let me update to 14.8 and see if I still have the problem, if I still do,
perhaps you can
give me some advice on how to get a better stack trace

2016-10-09 22:48:47 +0000 [error]: fluent/engine.rb:167:rescue in block in
log_event_loop: failed to emit fluentd's log event tag="fluent.trace"
event={"instance"=>70134216596880, "metadata_size"=>1, "message"=>"writin\
g events into buffer instance=70134216596880 metadata_size=1"}
error_class=NoMethodError error="undefined method `index' for nil:NilClass"
2016-10-09 22:48:47 +0000 [trace]: plugin/buffer.rb:165:add_metadata:
adding metadata instance=70134238286000 metadata=#<struct
Fluent::Plugin::Buffer::Metadata timekey=1476046800, tag=nil, variables=nil>

John Schneider
C 408 203 7891
E jottos@gmail.com

On Wed, Oct 19, 2016 at 8:18 PM, Masahiro Nakagawa <notifications@github.com

**Comment by repeatedly** [comment]
Ah, your log doesn't have stacktrace?
By default, fluentd dumps first stacktrace of error: http://docs.fluentd.org/articles/logging#suppress-repeated-stacktrace

**Comment by jottos** [comment]
I checked my startup options and I'm not suppressing stack traces, these
are the exact logs I'm seeing, this might be the entire trace

I just updated to the latest fluentd 0.14.8 and still get exceptions,
though is seems like many fewer and i looked at entire log I'm not sure if
the error is from the fluentd logger or the individual plugins. I did a
td-agent-gem install so I don't know if if got the 14.8b version

log just indicates:
2016-10-20 04:34:39 +0000 [info]: fluent/supervisor.rb:504:supervise:
starting fluentd-0.14.8
2016-10-20 04:34:39 +0000 [info]: fluent/supervisor.rb:447:run_worker:
starting fluentd-0.14.8 without supervision
2016-10-20 04:34:39 +0000 [info]: fluent/engine.rb:116:block in configure:
gem 'fluentd' version '0.14.8'
2016-10-20 04:34:39 +0000 [info]: fluent/engine.rb:116:block in configure:
gem 'fluentd' version '0.14.6'
2016-10-20 04:34:39 +0000 [info]: fluent/engine.rb:116:block in configure:
gem 'fluentd' version '0.12.29'

(just curious, why does the td-agent show configure statements for the old
fluentd gems?)

logs with exceptions below

/jos

2016-10-20 03:42:20 +0000 [warn]: emit transaction failed:
error_class=NoMethodError error="undefined method `[]' for nil:NilClass"
tag="fluent.info"
2016-10-20 03:42:20 +0000 [error]: failed to emit fluentd's log event tag="
fluent.info" event={"type"=>:copy, "plugin_id"=>"object:3ff2852ebca8",
"message"=>"closing output plugin type=:copy
plugin_id=\"object:3ff2852ebca8\""} error_class=NoMethodError
error="undefined method `[]' for nil:NilClass"
2016-10-20 03:42:20 +0000 [error]: failed to emit fluentd's log event tag="
fluent.info" event={"type"=>:gelf, "plugin_id"=>"object:3ff283732700",
"message"=>"closing output plugin type=:gelf
plugin_id=\"object:3ff283732700\""} error_class=NoMethodError
error="undefined method `index' for nil:NilClass"
2016-10-20 03:42:20 +0000 [warn]: emit transaction failed:
error_class=NoMethodError error="undefined method `index' for nil:NilClass"
tag="fluent.info"
2016-10-20 03:42:20 +0000 [error]: failed to emit fluentd's log event tag="
fluent.info" event={"type"=>:forest, "plugin_id"=>"object:3ff2836a8a8c",
"message"=>"closing output plugin type=:forest
plugin_id=\"object:3ff2836a8a8c\""} error_class=NoMethodError
error="undefined method `index' for nil:NilClass"˘
2016-10-20 03:42:20 +0000 [warn]: emit transaction failed:
error_class=NoMethodError error="undefined method `index' for nil:NilClass"
tag="fluent.info"
2016-10-20 03:42:20 +0000 [error]: failed to emit fluentd's log event tag="
fluent.info" event={"type"=>:grep, "plugin_id"=>"object:3ff283740af8",
"message"=>"closing output plugin type=:grep
plugin_id=\"object:3ff283740af8\""} error_class=NoMethodError
error="undefined method `index' for nil:NilClass"
2016-10-20 03:42:20 +0000 [error]: failed to emit fluentd's log event tag="
fluent.info" event={"type"=>:s3, "plugin_id"=>"object:3ff2843c2718",
"message"=>"closing output plugin type=:s3
plugin_id=\"object:3ff2843c2718\""} error_class=NoMethodError
error="undefined method `index' for nil:NilClass"



John Schneider
C 408 203 7891
E jottos@gmail.com

On Wed, Oct 19, 2016 at 9:55 PM, Masahiro Nakagawa <notifications@github.com

**Comment by repeatedly** [comment]
From the logs, you hit same error with other plugins.
It seems reproducible problem, could you show me the configuration?

**Comment by jottos** [comment]
John Schneider
C 408 203 7891
E jottos@gmail.com

On Thu, Oct 20, 2016 at 1:16 AM, Masahiro Nakagawa <notifications@github.com

**Comment by repeatedly** [comment]
And if you have a reproducible, write it together is very helpful.

**Comment by jottos** [comment]
the test is pretty simple. It's my standard stress test, I send a constant
stream of logs to the fluentd single threaded, from several different
sources (different machines in my AWS infrastructure, usually 1million from
each source, the test is run via an Ansible script that runs the test
programs from a single box) I then count them at each destination using SQL
(apache Drill) for HDFS and other programs for Kafka and S3. this issue can
be reproduced just using one log sender client 1M logs is probably way more
than is needed

The source to our test driver below


John Schneider
C 408 203 7891
E jottos@gmail.com

On Mon, Oct 24, 2016 at 2:00 PM, Masahiro Nakagawa <notifications@github.com

**Comment by repeatedly** [comment]
Which is test driver code?

**Comment by jottos** [comment]
Sorry, this is in python and not ruby :)

The basic options are
-s <server> choose server from list of built in servers
-t <test-iterations>   number of test runs to do (default 1)
-n <number of logs> number of logs to send per test (default 1,000,000)

Example commands:

  python3 fluent_test.py -s fluent-1.apixio.com
  python3 fluent_test.py -s fluent-1.apixio.com -t 10
  python3 fluent_test.py -s fluent-1.apixio.com -t 50 -n 100000

(note the python3 environment needs the 'fluent-logger' package installed)

so I set up the system to use a set of hard coded fluent servers. these are
my production servers. you can alter this list.

  production_servers = ['fluent-1.apixio.com', 'fluent-2.apixio.com', '
fluent-3.apixio.com', 'fluent-4.apixio.com']

there is an additional server called 'local' you can choose that will talk
to a fluent running on your local machine.
In my test environment my local server relays to one of my production
servers

  python3 fluent_test.py -s local

the config on 'local' server is setup to forward to all of the fluent-?.
apixio.com servers
this is the mechanism I use normally to test, since it replicates the
behavior of my normal
servers buffering on a local fluent which relays to my fluent agregator
servers

To help you out I have added another server parameter '-S' which will allow
you to specify
the server you want to point at

  python3 fluent_test.py -S <a server FQDN or IP-address>

I run my tests via ansible. Typically I set up server test servers and run
a relay from them to the main server

  ansible test-server-1 -m shell -a "cd /home/jschneider/fluent_test;
source ft_env/bin/activate; nohup python fluent_test.py -s local -t 10&"

I would run this command on several test clients that point at my
production fluent pool

I have included the new test program with the -S added


John Schneider
C 408 203 7891
E jottos@gmail.com

On Mon, Oct 31, 2016 at 3:59 PM, Masahiro Nakagawa <notifications@github.com

**Comment by kenhys** [comment]
v0.14 series is not maintained anymore, I'll close it.
