### ISSUE TITLE
Colons in filename cause "The specified key does not exist." on input plugin

### ISSUE THREAD

**Issue by spaelet** [fluent/fluent-plugin-s3#172]
Log files dropped onto S3 by AWS Config have colons in the filename, e.g.:
```
189443738264_Config_us-east-1_ConfigHistory_AWS::EC2::Volume_20161023T001646Z_20161023T001646Z_1.json.gz
```
which seem to cause the ingest to fail, throwing errors like:
```
2016-10-23 01:56:46 +0000 [warn]:  error_class=Aws::S3::Errors::NoSuchKey error="The specified key does not exist."
```
When you rename the file without colons, it works fine.

**Comment by repeatedly** [comment]
Error seems to happen inside AWS Ruby client.
Do you know this problem is AWS spec issue or client implementation issue?

**Comment by spaelet** [comment]
S3 docs say colons are okay to use but "might require special handling":
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys
I'll do a little further experimentation and then open an issue on the ruby client
Thanks!
