### ISSUE TITLE
s3_object_key_format support %{tag}

### ISSUE THREAD

**Issue by breath-co2** [fluent/fluent-plugin-s3#179]
for #31 

add one param: remove_tag_prefix

config example:
```
<match test.*>
    @type s3
    ... some s3 config 

    path test/
    remove_tag_prefix test.
    time_slice_format %Y/%m/%d
    s3_object_key_format "%{path}%{time_slice}/%{tag}_%{index}.%{file_extension}"
</match>
```

save file by tag like this:

- /test/2016/12/29/create_0.log
- /test/2016/12/29/login_0.log
- /test/2016/12/30/create_0.log
- /test/2016/12/30/login_0.log

**Comment by repeatedly** [comment]
Latest v1 based S3 plugin supports this

**Comment by prtk-ngm** [comment]
same configuration is not working with 1.1.11 version out_s3 plugin

**Comment by ganmacs** [comment]
> same configuration

Could you show us the full configuration?
