### ISSUE TITLE
Do not override configured s3_object_key_format with disabled check_object

### ISSUE THREAD

**Issue by mmaslowskicc** [fluent/fluent-plugin-s3#181]
My use case is uploading logs to S3, with UUIDs in their keys (from `%{uuid_flush}`), and using only the consistent subset of S3 operations (so other services can list the logs in the S3 bucket and know that they won't be not found when a different service requests them). With my understanding of <http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel>, this requires configuring `out_s3` with `check_object false`.

But there is
```
      if !@check_object
        @s3_object_key_format = "%{path}/%{date_slice}_%{hms_slice}.%{file_extension}"
      end
```
which overrides the custom `s3_object_key_format` that I use to pass the UUID and other specific elements in the key.

**Comment by repeatedly** [comment]
@chillaxd Could you check this?

**Comment by chillaxd** [comment]
@mmaslowskicc if check_object is false that means fluentd_s3 plugin will not check for the object existence in s3. So, to avoid override all the objects must have some unique id every time it is going to s3. That's why the format has been fixed.
Now in your use case, you are trying to send UUID and other specific elements in the log content, not as it's name. Correct me please, if I'm misunderstood you use case.
And, s3_object_key_format will be used for uploaded log's name not as their content.

**Comment by fizyk** [comment]
@chillaxd there's nothing mentioning log content, only object keys, which @mmaslowskicc mentions we're adding uuid to (to the key, not content - apart from other elements making it even more unique like hostname).

Currently with check_object set to true, the check itself creates the key (with no content) making other services list, but error when trying to access the file.

Simplest way to avoid these errors would be to set check_object to false, but then, the key_format is being set arbitrary to the path that's not desired by us.

**Comment by chillaxd** [comment]
@mmaslowskicc @fizyk ok I got the usecase. So I think there should be some provision to use own format other than the default one (which is the current one). But in that case user would be responsible for any data loss. As if the object with same name exist, it will override in S3. I know you know that, still mentioning.

**Comment by fizyk** [comment]
yup, personally I think a documentation warning near the check_object would be sufficient for users.

**Comment by kenhys** [comment]
TODO: document it to https://github.com/fluent/fluent-plugin-s3/blob/master/docs/output.md

**Comment by kenhys** [comment]
#380 was merged.

I'll close this.
