### ISSUE TITLE
#{Socket.gethostname} does not work

### ISSUE THREAD

**Issue by islue** [fluent/fluent-plugin-s3#184]
I got such a warning with v0.8.1
```
%{hostname} will be removed in the future. Use "#{Socket.gethostname}" instead
```

My config is
```
s3_object_key_format %{path}%{time_slice}.%{index}.#{Socket.gethostname}.%{file_extension}
```
And I got file named as below
```
access_log.2017-02-20T07.1.#{Socket.gethostname}.gz
```
In the test code, it seems that #{Socket.gethostname} does work under ruby double quotation mark context. But I couldn't find the way it works in read codes. Am I missing something?

**Comment by repeatedly** [comment]
See: http://docs.fluentd.org/v0.12/articles/config-file#embedded-ruby-code

**Comment by islue** [comment]
Got it. Thank you.

**Comment by repeatedly** [comment]
I will update README with actual example.
