### ISSUE TITLE
Inconsistent timezone for time_slice_format

### ISSUE THREAD

**Issue by akirakiron** [fluent/fluent-plugin-s3#190]
We're formatting time_slice_format with hard-coded UTC right now.
Here is [the snippet](https://github.com/fluent/fluent-plugin-s3/blob/master/lib/fluent/plugin/out_s3.rb#L207)
```
      time_slice = if metadata.timekey.nil?
                     ''.freeze
                   else
                     Time.at(metadata.timekey).utc.strftime(time_slice_format)
                   end
```
This is inconsistent and confusing since we apply timekey_zone in the other part (e.g. path) or in the other output plugins. Is it possible to unify them?

**Comment by blogwatcher-gi** [comment]
Time.at(metadata.timekey).utc.strftime(time_slice_format)
=>
 @buffer_config['timekey_use_utc'] ? Time.at(metadata.timekey).utc.strftime(time_slice_format) : Time.at(metadata.timekey).strftime(time_slice_format)

**Comment by repeatedly** [comment]
Sorry for the late. I will check this soon.

**Comment by repeatedly** [comment]
I wrote a patch: https://github.com/fluent/fluent-plugin-s3/pull/194
Could you check this?
