### ISSUE TITLE
how can i use it in china

### ISSUE THREAD

**Issue by jiachenzhong** [fluent/fluent-plugin-s3#199]
edpoint default is .amazonaws.com 
but in china is .amazonaws.com。cn

**Comment by repeatedly** [comment]
Use `s3_endpoint`.

**Comment by jiachenzhong** [comment]
<match s3.apache.access>
    @type s3
    aws_key_id xxxxxx
    aws_sec_key xxxxxx
    s3_bucket XXX
    s3_region cn-north-1
    s3_endpoint amazonaws.com.cn
    path logs/
    buffer_path /var/log/fluent/s3
    time_slice_format %Y%m%d%H
    time_slice_wait 10m
    buffer_chunk_limit 256m
  </match>


unexpected error error_class=ArgumentError error=#<ArgumentError: expected :endpoint to be a HTTP or HTTPS endpoint>

what can i do now?

**Comment by jiachenzhong** [comment]
s3_endpoint https://s3.cn-north-1.amazonaws.com.cn
there is no more error but no data be send to s3 bucket

**Comment by repeatedly** [comment]
Hmm... fluent-plugin-s3 uses aws-sdk-ruby.
Could you check aws-sdk-ruby works with your environment?
