### ISSUE TITLE
AWS SDK for Ruby V3

### ISSUE THREAD

**Issue by riywo** [fluent/fluent-plugin-s3#208]
Hi,

AWS SDK for Ruby V3 has been announced generally available, but the dependency of this plugin v1.0.0 RC is still declared by less than v3.

Why don't you update it to include v3 or only v3 at this timing? Do you have any concern to use v3?

See also: https://aws.amazon.com/blogs/developer/announcing-the-modularized-aws-sdk-for-ruby-version-3/

Best,

**Comment by repeatedly** [comment]
Sorry for the late.

For keeping to support aws-sdk v2, do we need following code?

```
begin
  require 'aws-sdk-s3'
rescue LoadError
  require 'aws-sdk'
end
```

**Comment by repeatedly** [comment]
Latest fluent-plugin-s3 uses v3.
