### ISSUE TITLE
support for parquet compression

### ISSUE THREAD

**Issue by mattyb** [fluent/fluent-plugin-s3#221]
We're looking in to using fluentd to write logs to S3, where they'll be read by AWS Redshift Spectrum. Spectrum charges by read throughput, but it also supports the columnar compression format of Parquet, which can greatly reduce the amount of data you have to scan through. It would be great if the s3 plugin could support this compression format.

**Comment by repeatedly** [comment]
s3 plugin's format or compression are pluggable.
So if you write the plugin, you can use parquet format in s3 output.
But I'm not sure how parquet processes event streams...

**Comment by dobesv** [comment]
Looks like there is a plugin that supports parquet:

https://github.com/joker1007/fluent-plugin-arrow

**Comment by freelancerlucas** [comment]
Thanks for sharing. Is there someone who uses that plugin (fluent-plugin-arrow) somewhere? Thanks for any feedback, I haven't checked the code yet.

**Comment by eredi93** [comment]
@freelancerlucas did you end up trying the https://github.com/joker1007/fluent-plugin-arrow plugin?

I also want to have Parquet events in S3 and looking at how i can achieve that

**Comment by eredi93** [comment]
@dobesv have you tried the plugin? i just found an issue: tl;dr it doesn't work with the current version of `td-agent`

**Comment by dobesv** [comment]
I tried to get it working but it seems to crash if I give it data that doesn't match the schema.  It's still a work in progress for me, but now I'm thinking I'll output JSON and run another process to periodically convert JSON to Parquet instead.

**Comment by freelancerlucas** [comment]
Thanks guys for the input, today I just started working on this topic. I will let you know about the progress, but I was also thinking about running another process to convert JSON to Parquet.

**Comment by okkez** [comment]
We are developing the compressor for the parquet format.
We will create a PR to publish the compressor or create a new gem to publish it.
The compressor depends on the external command we are developing.

Which is prefer creating a PR or a gem?

**Comment by eredi93** [comment]
Awesome @okkez could update this issue when you have something?
also happy to help if you need a hand

**Comment by repeatedly** [comment]
parquet is now popular and it doesn't depend on external gems.
So support it in s3 plugin seems better. Could you send a PR?

**Comment by eredi93** [comment]
@repeatedly what do you mean it doesn't depend on external gems? 
 it would require https://github.com/apache/arrow/tree/master/ruby/red-parquet no?

**Comment by okkez** [comment]
OK, I will create new PR to add parquet compressor after we test it our environment.

**Comment by shevisjohnson** [comment]
@okkez any progress to report on this PR? Parquet formatting would be very useful, so I'd be happy to contribute if there is still work to be done.

**Comment by realknorke** [comment]
We would GREATLY appreciate Parquet support for fluent.

**Comment by okkez** [comment]
@shevisjohnson @realknorke Could you try #338 ?

**Comment by realknorke** [comment]
> @shevisjohnson @realknorke Could you try #338 ?

Sorry, not feasable for us because columnify is not mature enough. For a test run I tried to convert a simple TSV file to parquet (all columns in schema set to type "string"). The process failed because in some columns the value is  NAN or INF (valid locodes for regions in France). Also, the columnify tools is eating up a lot of memory because the columnization is done in memory. This may not be a problem in most cases, but its a huge problem as part of a (relatively) small fluent logging container, writing a lot of data per day. You don't want peaks in memory consumtion (cpu peaks may be okay to some degree)

**Comment by okkez** [comment]
@realknorke Thank you for testing columnify.
We are trying to improve memory usage https://github.com/reproio/columnify/pull/52

Please create a new issue on https://github.com/reproio/columnify/issues if you have problems to use columnify.

**Comment by okkez** [comment]
Columnify v0.1.0 has been released.
https://github.com/reproio/columnify/blob/v0.1.0/CHANGELOG.md
>  Implement stream-based input record decoder's to reduce memory consumption.

**Comment by abicky** [comment]
If you want some examples, the repository https://github.com/abicky/docker-log-and-fluent-plugin-s3-with-columnify-example might be helpful.

**Comment by realknorke** [comment]
@okkez sorry, took me some time to get priority on this issue.
I successfully integrated columnify as a compression flavor for s3 in fluentd (your ruby example basically).
I'm going to test columnify-fluent in more depth starting monday and with high load. :)
But it looks very promising now. I'll keep you informed.

**Comment by 123BLiN** [comment]
It seems such plugin can also be some kind of schema validator to only allow "good" messages went to s3, because in our case later Athena breaks in case schema has been changed

**Comment by abicky** [comment]
FYI, fluent-plugin-s3 1.6.0 including the changes in https://github.com/fluent/fluent-plugin-s3/pull/338 has been released.

**Comment by ashie** [comment]
Thanks for notifying it.
Yes, it's already released.
I close this issue.
