### ISSUE TITLE
The value of %H for path or s3_object_key_format is always 00

### ISSUE THREAD

**Issue by asumawang** [fluent/fluent-plugin-s3#229]
Hi,

Why is %H always 0 for path or s3_object_key_format?

Here's my config:

```
<match s3.*.*>
  @type s3

  aws_key_id xx
  aws_sec_key xx

  s3_bucket mylogs
  path v2/%Y/%m/%d/%H/
  s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
  time_slice_format %Y%m%d%H
  store_as json

  <format>
    @type json
  </format>

  <buffer time>
    timekey 1h
    @type file
    path /var/log/td-agent/buffer/
    timekey_wait 10m
    chunk_limit_size 50m
  </buffer>
</match>

```
Thanks!

**Comment by sampointer** [comment]
I also have the same problem of `%H` and `%M` returning 00. Here is the configuration I am using:

```
    @type s3
    s3_bucket topsecretbucketname
    s3_region eu-west-1

    # https://cwiki.apache.org/confluence/display/Hive/LanguageManual+Types#LanguageManualTypes-timestamp
    time_format %Y-%m-%d %H:%M:%S.%L
    include_time_key true

    time_slice_format year=%Y/month=%m/day=%d/hour=%H/minute=%M
    path "ec2"
    s3_object_key_format "%{path}/%{time_slice}/instance=i-12345678901234567/i-12345678901234567-%{index}.json"
    format json
    store_as json

    auto_create_bucket false
    check_bucket false
    check_object true

    buffer_type file
    buffer_path /var/spool/td-agent/s3
    # 1Gb of buffer
    buffer_chunk_limit 5m
    buffer_queue_limit 200

    # Attempt to flush the file buffer on shutdown as in AWS hosts being shut
    # down are very likely to be being terminated.
    #
    flush_at_shutdown true

    # Support ms time resolution
    time_as_integer false
```

The bucket and path naming is to allow querying of the data via AWS Athena.

**Comment by sampointer** [comment]
I've noticed that removing all buffer files related to previous configurations is the only thing that will cause amendments to the `time_slice_format` to be effected if fluentd was unable to flush previous buffers (due, perhaps, to duplicate keys in the s3 bucket

**Comment by kakmt** [comment]
Similar issue happened to me.
My case is `%M` in `time_slice_format` is always substituted to `00` with `timekey 3600`.
(eg.: `time_slice_format %Y%m%d/%H%M` -> `20180828/1100`)

But after changing`timekey` to `60` this doesn't occur and works correctly.

Environment:
- fluentd (1.2.4)
- fluent-plugin-s3 (1.1.4)

**Comment by repeatedly** [comment]
Hmm... I re-check this issue again but it worked on my environment with asumawang's buffer configuration.

- conf

```
<match s3.**>
  @type s3

  s3_bucket fluent-plugin-s3-test
  path test/ts_%Y%m%d%H/
  s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
  time_slice_format %Y%m%d%H
  <format>
    @type json
  </format>
  <buffer time>
    timekey 1h
    @type file
    path /tmp/td-agent/buffer/
    timekey_wait 10m
    chunk_limit_size 50m
    flush_at_shutdown true
  </buffer>

  <assume_role_credentials>
    # Use my credential
  </assume_role_credentials>
</match>
```

- object path

`
fluent-plugin-s3-test/test/ts_2018082917/2018082917_0.gz
`

- env

fluentd: v1.2.5
fluent-plugin-s3: v1.1.4

@kakmt If you use `%M`, you need to use `timekey 60`. If you use `timkey 3600`, values are stored into 1 hour range and it doesn't have %M precision: https://docs.fluentd.org/v1.0/articles/buffer-section#time
