### ISSUE TITLE
Logs pushed to s3 are sometimes incomplete

### ISSUE THREAD

**Issue by mightwork** [fluent/fluent-plugin-s3#233]
My application writes logs to a file which fulentd tails and pushes to s3 every 10 mins. Sometimes these files do not contain all the logs. For example yesterday, 5 consecutive files being pushed to s3 started and ended at the following lines numbers from the main log file.

10.json
S 355508
E 493247

20.json
S 722455
E 984158

30.json
S 1105528
E 1497162

40.json
S 1497163
E 1906154

50.json
S 1906155
E 2052295

Here, the start and end of files 10.json, 20.json and 30.json don't match but subsequent ones match. This is not present today. Also, weirdly, fluentd reads from the same file and send the logs to elasticsearch as well. There all the logs are present. 
It seems like fluentd tail stopped working or it didn't write to buffer. My application writes about 600 lines of logs per second to the file. But if rate was the issue, the the elasticsearch plugin would also face problems but it's working fine.

My config:

```
<source>
  @type tail
  format json
  read_from_head true
  path PATH
  exclude_path EXCLUDE_PATH
  pos_file POS_FILE
  tag s3
</source>

<match s3>
  @type s3

  aws_key_id KEY
  aws_sec_key SECRET
  s3_region REGION
  s3_bucket BUCKET
  path PATH
  s3_object_key_format FORMAT
  <buffer time>
    @type file
    path PATH
    timekey 600
    timekey_wait 30
    compress gzip
    flush_at_shutdown true
    chunk_limit_size 256m
  </buffer>

  <format>
    @type json
  </format>

  time_slice_format %Y-%m-%d-%H
</match>
```

Fluentd logs also show no warning or error. Using fluentd version 1.1.3

**Comment by repeatedly** [comment]
600 msgs/sec is smaller so rate is not the problem.
Do you use same s3_object_key_format between multiple fluentd process?

**Comment by mightwork** [comment]
> Do you use same s3_object_key_format between multiple fluentd process?

Fluentd is running as a single process.

**Comment by mightwork** [comment]
I went through https://docs.fluentd.org/v0.10/articles/performance-tuning and it helped. Though I am not able to set the num_threads param. Getting the following error:

```
[warn]: parameter 'num_threads' in <match s3>
  @type s3
  num_threads 4
  aws_key_id xxxxxx
  aws_sec_key xxxxxx
  s3_region xxxx
  s3_bucket xxxxx
  path xxxxx
  s3_object_key_format xxx
  store_as "gzip"
  time_slice_format %Y-%m-%d-%H
  <buffer time>
    @type "file"
    path xxx
    timekey 600
    timekey_wait 30
    flush_at_shutdown true
    chunk_limit_size 256m
  </buffer>
  <format>
    @type "json"
  </format>
</match> is not used.
``` 

Am I setting it incorrectly? Also, I am seeing a lot of slow_flush_log_threshold messages.
```
[warn]: #0 buffer flush took longer time than slow_flush_log_threshold: elapsed_time=24.972010107710958 slow_flush_log_threshold=20.0 plugin_id="object:2acc98fea42c"
```

Does slow_flush_log_threshold effect fluentd's performance? And is increasing them a solution?

**Comment by repeatedly** [comment]
> Though I am not able to set the num_threads param. Getting the following error:

Ah, this is v0.12 style example. We will update the document with v1 style soon.
In v1, you use `flush_thread_count` in `<buffer>` instead.

> Does slow_flush_log_threshold effect fluentd's performance? And is increasing them a solution?

No, it doesn't affect the performance.

**Comment by repeatedly** [comment]
Ah, you refers outdated document. I misread the link. I thought v1, not v0.10.

**Comment by mightwork** [comment]
Got it. Thanks :)

**Comment by discordianfish** [comment]
> Ah, this is v0.12 style example. We will update the document with v1 style soon.
> In v1, you use `flush_thread_count` in `<buffer>` instead.

Since I just came across this, just a little reminder that the docs still use the old syntax.
