### ISSUE TITLE
Readme documentation typo

### ISSUE THREAD

**Issue by ecristea** [fluent/fluent-plugin-s3#234]
This is about a small typo:

In paragraph `Use your (de)compression algorithm` first sentence contains:
`... like Fleuntd's ...`
probably should be changed to
`... like Fluentd's ...`

**Comment by cosmo0920** [comment]
Hi.
Thanks foe the report.
Could you send a patch to fix typo?

**Comment by ecristea** [comment]
Created:
https://github.com/fluent/fluent-plugin-s3/pull/235

**Comment by DStorck** [comment]
fixed by #235 and already merged, this can be closed

**Comment by okkez** [comment]
Thanks!
