### ISSUE TITLE
The plugin works good as expected, but it fail to clean up the logs after pushing to S3

### ISSUE THREAD

**Issue by Sam123ben** [fluent/fluent-plugin-s3#237]
Do the plugin have some or any feature to enable auto clean up the logs that once its pushed to S3 as its getting accumulated to logs directory in the ndoe and increasing the diskspace.

Regards,
Samyak

**Comment by prachetasp** [comment]
Logrotate perhaps?

**Comment by repeatedly** [comment]
Do you mean file buffer's files?
It should be deleted after uploaded.
Is your problem reproducible?

**Comment by umutkocasarac** [comment]
Hi,
I am also facing the same issue. I am not sure what could I provide you for further investigation.  My s3 configuration could be found at the below. Fluentd plugin should send the logs in a hour but I could still see the buffer* files belongs to 4 days before.

<store>
        @type s3
        s3_bucket name_ofthe_bucket
        s3_region us-east-1
        path prod/
        <buffer tag,time>
            @type file
            path /var/log/fluent/s3
            timekey 3600 # 1 hour partition
            timekey_wait 10m
            timekey_use_utc true # use utc
            chunk_limit_size 256m
        </buffer>
        time_slice_format %Y%m%d%H
      </store>

**Comment by paulorsbrito** [comment]
The same here. Because of this, I'm getting "too many open files" and have to clear logs manually now and then.

**Comment by Ramneekkhurana** [comment]
is SQS a must ?

**Comment by ZP-AlwaysWin** [comment]
Hello, has this problem been solved
@

**Comment by ZP-AlwaysWin** [comment]
Hi @repeatedly ,  has this problem been solved, I also encountered the problem that the files in the buffer could not be automatically deleted after the push。

```
<match>
<buffer>
@type file
path /etc/fluentd/temp/moons
timekey_wait 5
timekey      1
chunk_limit_size 256m
</buffer>
time_slice_format %Y%m%d%H

</match>
```
![image](https://user-images.githubusercontent.com/23489782/87045442-7aa0e080-c22a-11ea-9841-c8a13983fcfa.png)

**Comment by ZP-AlwaysWin** [comment]
> is SQS a must ?

What does this parameter SQS mean?
