### ISSUE TITLE
unexpected error error_class=Seahorse::Client::NetworkingError error="execution expired"

### ISSUE THREAD

**Issue by vimalmpatel** [fluent/fluent-plugin-s3#240]
i am using fluent-plugin-s3 -v 1.0.0 on docker 
 
here is my configuration for s3 input 

```aconf
<source>
  @type s3
  tag s3access
  s3_region "us-east-1"
  <assume_role_credentials>
   role_arn  "#{ENV['AWS_ROLE_ARN']}"
   role_session_name DZO
  </assume_role_credentials>
  s3_bucket "XXXXX"
  <sqs>
    queue_name "XXXXXX"
  </sqs>
</source>
```

i am getting Seahorse::Client::NetworkingError: execution expired error

**Comment by vimalmpatel** [comment]
@cosmo0920 anyone looking into this issue ?

**Comment by cosmo0920** [comment]
It is connectivity issue.
Did you get large object from S3?
See: https://github.com/aws/aws-sdk-ruby/issues/1034

**Comment by vimalmpatel** [comment]
@cosmo0920 it is very small file. i tried with every possible option here. s3 output works fine with different config. s3 input only causing this issue.

here is my latest config file.

**Comment by cosmo0920** [comment]
in_s3 had been written by @okkez.
@okkez Dou you know why this error ocurrs?

**Comment by lel085** [comment]
I am getting below error 
2018-10-08 16:38:14 +0000 [error]: #0 unexpected error error_class=Seahorse::Client::NetworkingError error="execution expired"
@okkez Can you please say why this errors? Any solution to fix the issue?

**Comment by jayhding** [comment]
@vimalmpatel @lel085 could you turn on fluentd debug log level so more logs can be seen?
Reference: https://docs.fluentd.org/v1.0/articles/logging

I just found bugs of setting up proxy for S3 and SQS in the code, see https://github.com/fluent/fluent-plugin-s3/pull/254

However, to me looks like your failure reason is different.

**Comment by repeatedly** [comment]
If the plugin's authn/authz setting has a problem, API returns an error.
But this case is timeout. It means HTTPS request is blocked by something.
Need debug information to debug which point is timedout.
