### ISSUE TITLE
works fine on my laptop when tailing logs but fails when trying to log from docker-compose

### ISSUE THREAD

**Issue by timuckun** [fluent/fluent-plugin-s3#251]
I have the following configuration
 ```
<source>
  @type tail
  path /...../test.log

  pos_file //....../test.log.pos 
  tag foobar.tsv #fluentd tag!
  format syslog
  
</source>

<match **>
 @type s3
  aws_key_id xxxxxx
  aws_sec_key xxxxxx
  s3_bucket gs
  s3_region ap-southeast-2
  check_apikey_on_start true
 </match>
```

I can fill that file and it ships the logs to S3 no problem.

I then create a container with fluentd and this plugin and try to ship docker logs the configuration is the same as above except the source is now

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>
```

The fluentd container comes up, the stdout output works. I can see the logs on the screen, there are no errors  but nothing shows up on S3.  

How can I figure out what the problem is.

**Comment by jordo1138** [comment]
in the end just follow this guide, save a ton of time and do the filtering/concatenating first for sending to s3, your source and match need to change if you're using the default docker logging also
https://docs.fluentd.org/v0.12/articles/docker-logging

<match **>
    @type stdout
</match>
```

**Comment by jordo1138** [comment]
@timuckun if you followed that guide I assume you have fluentd as the docker logging driver?
You can trouble shoot this to see..i think your match isn't working or your logging driver isn't set to fluentd..the default is json
```
<match docker.*>
    @type stdout
</match>
```
