### ISSUE TITLE
How-to monitor s3 uploads lagging behind?

### ISSUE THREAD

**Issue by Trane9991** [fluent/fluent-plugin-s3#261]
Hello.
We are using fluentd to do some events processing and uploading to s3.
Once we just start using it uploads started to lag behind until we increased `flush_thread_count`. I want to prevent this happening in the future (or at least to be notified when this happens), So I enabled the `monitoring_agent` source and configured metrics publishing to AWS CloudWatch, so the question is, what metrics to look at?

There are 2 relevant metrics:
`buffer_queue_length` and `buffer_total_queued_size` and I'm not sure which one is better to look at.

Do I understand correctly, that `buffer_queue_length` reflects the number of chunks that queued for upload so if uploads will start to lag behind, `buffer_queue_length` value will grow?

Is configuring an alarm for `buffer_queue_length >  0` will be enough?

**Comment by repeatedly** [comment]
> Is configuring an alarm for buffer_queue_length > 0 will be enough?

`> 1` is correct, right?

It depends on your traffic.
If your traffic is large, sometimes buffer_queue_length is largar than 1.
In addition, if AWS S3's API or your network has a temporal problem, buffer_queue_length is also larger than 1.
If you want to monitor any problem, lower alert setting is fit I think.
