### ISSUE TITLE
S3 output hardcodes amazon domain

### ISSUE THREAD

**Issue by matt14483** [fluent/fluent-plugin-s3#263]
The s3 output plugin takes the region, bucket name, and assumes amazonaws.com for the s3 endpoint.  However, some other environments do not use amazonaws.com, and rather a different domain for the s3 endpoint.  If we can make that a parameter, I can avoid a DNS mess to get my data to the proper endpoints.

**Comment by repeatedly** [comment]
You can use s3_endpoint for that case: https://github.com/fluent/fluent-plugin-s3#configuration-output

**Comment by boenr1** [comment]
The s3_endpoint is deprecated: https://docs.fluentd.org/output/s3

```
This option is deprecated because latest aws-sdk ignores this option. Please use s3_region instead.
The Amazon S3 enpoint name. Please select the appropriate endpoint name from the list below and confirm that your bucket has been created in the correct region.
```
So is there another possibility? I also want to use the s3 output with an storage grid S3 and not AWS.

**Comment by repeatedly** [comment]
s3_endpoint should work with compatible service. Check s3_endpoint in README: https://github.com/fluent/fluent-plugin-s3

We will remove s3_endpoint from official article because it is deprecated for main purpose...

**Comment by kenhys** [comment]
Resolved by https://github.com/fluent/fluent-plugin-s3/issues/263#issuecomment-451672862
