### ISSUE TITLE
AWS Signature Version 2 Deprecation for Amazon S3: AWS-SDK version 3 support?

### ISSUE THREAD

**Issue by shigemk2** [fluent/fluent-plugin-s3#267]
AWS document says:

> Signature Version 2 is being deprecated in Amazon S3, and the final support for Signature Version 2 ends on June 24, 2019. After June 24, 2019, Amazon S3 will only accept API requests that are signed using Signature Version 4.

https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html

AWS tells us to upgrade to Ruby V3.

Do you have any plans?

**Comment by cosmo0920** [comment]
We already supported and depended on AWS SDK v3:
https://github.com/fluent/fluent-plugin-s3/blob/master/fluent-plugin-s3.gemspec#L21

AWS SDK uses Signature Version 4: https://github.com/aws/aws-sdk-ruby/blob/master/gems/aws-sdk-s3/lib/aws-sdk-s3/plugins/s3_signer.rb

Do you have a trouble for AWS Signature Version 2 in this plugin?

**Comment by shigemk2** [comment]
@cosmo0920 
Sorry for my misunderstanding. 
I confused aws-sdk-s3 with aws-sdk. fluent-plugin-s3 will use version 3 aws-sdk by installing aws-sdk-s3.

https://github.com/aws/aws-sdk-ruby#installation
