### ISSUE TITLE
Logs shipped with wrong timestamp and timekey ignored

### ISSUE THREAD

**Issue by serain** [fluent/fluent-plugin-s3#273]
I want to ship my logs to s3. Based on [this issue](https://github.com/fluent/fluent-plugin-s3/issues/187) I did this:

```
<source>
  @type tail
  path /var/log/vault_audit.log
  pos_file /var/log/td-agent/vault.audit_log.pos
  <parse>
    @type json
  </parse>
  tag s3.vault.audit
</source>

## s3 output
<match s3.*.*>  
  @type s3

  s3_bucket my-bucket
  path logs/

  <buffer>
    @type file
    path /var/log/td-agent/s3
    timekey 1800
    timekey_wait 5m
    chunk_limit_size 256m
  </buffer>

  time_slice_format %Y/%m/%d/%H%M
</match>  
```

What I'd expect is for my logs to be shipped to S3 every 30 minutes, and be formatted in directories as ie: `logs/2019/05/01/1030`

Instead my logs are shipped every 2-3ish minutes on average, and the output time format in S3 is starting from the epoch ie: `logs/1970/01/01/0030_0.gz`

(the time is correctly set on my system)

**Comment by qburst-anoop** [comment]
@serain How will you fix this issue?

**Comment by caleb15** [comment]
I ran into the same issue with the timekey :( 

![image of comic link below](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

https://xkcd.com/979/
