### ISSUE TITLE
Need log filenames to contain %M but don't want a file per minute

### ISSUE THREAD

**Issue by dvfeinblum** [fluent/fluent-plugin-s3#276]
I've looked at the previously closed issues and none of them address this use case.

I'd like fluent to cut logs every 5 minutes, but I need the minute value to be in the log name. So, in my bucket, I'd want to see:

```
/2019/06/05/05-logname.log.gz
/2019/06/05/10-logname.log.gz
/2019/06/05/15-logname.log.gz
```

I know how to achieve this by altering my `time_slice_format` to be `%Y/%m/%d/%H/%M-` and then setting `s3_object_key_format` to `%{time_slice}logname.log.%{file_extension}`, but updating this parameter causes me to get a file per minute.

I've read the fluentd docs and I understand that this behavior is expected, but why can't `flush_interval` take priority over the structure of the time stamp? It seems weird for these contracts to be tied up with one another (the shape of the filename and the time that files are cut).

Is there anyway around this I might be missing?

**Comment by repeatedly** [comment]
`timekey 300` and time based placeholder don't work?
I'm not sure why you use v0.12's `time_slice_format` in v1.

https://github.com/fluent/fluent-plugin-s3#v10-style

**Comment by dvfeinblum** [comment]
Ah; this explains quite a bit. It turns out we're still back on v0.12.40. I'll see about upgrading.

On the off chance that we can't upgrade, is there a way to set `timekey` via the older config? Thanks for your quick response!

**Comment by kenhys** [comment]
Solved via https://github.com/fluent/fluent-plugin-s3/issues/276#issuecomment-499359724
