### ISSUE TITLE
S3 Input: Need S3 Meta-information like Path in bucken

### ISSUE THREAD

**Issue by kochp** [fluent/fluent-plugin-s3#277]
Hi everybody, 

I am using the Plugin as imput from an S3 bucket. 
Therefore the files will be stored in a specific path blow the S3 bucket. This Information is important for me to know. 

Is there a possibility to add this meta information to the Log-Message or as part of the tag? 

I did not find any option in the direction or did I miss something?

**Comment by atkinsj** [comment]
+1. Having the object key exposed as a variable to be used in routing would be helpful.

**Comment by kochp** [comment]
I just found this pull request (https://github.com/fluent/fluent-plugin-s3/pull/220) and tried with an locally created gem based on that PR and it worked fine. 

I am just wondering why it is not merged into the this project.

**Comment by ganmacs** [comment]
FYI: https://github.com/fluent/fluent-plugin-s3/releases/tag/v1.1.11 released

https://github.com/fluent/fluent-plugin-s3/blob/15915d83e9461929e19a78fa0d5a01fbcf6ceb39/ChangeLog#L1-L4
