### ISSUE TITLE
One SQS queue per S3 bucket?

### ISSUE THREAD

**Issue by atkinsj** [fluent/fluent-plugin-s3#280]
Could you confirm if SQS queues should map 1-1 to S3 buckets or if we can have multiple <source> @type s3 </source> attached to one SQS queue?

**Comment by repeatedly** [comment]
@okkez Could you check?

**Comment by sonalkr132** [comment]
any word on this? Seems like we are using bucket defined in `s3` config to get keys in `sqs`. so this must be a requirement?
https://github.com/fluent/fluent-plugin-s3/blob/8e344e21ff611d6fe7dc52241963cb4a44ef0beb/lib/fluent/plugin/in_s3.rb#L264

**Comment by okkez** [comment]
We should use one SQS queue per one s3 input plugin section.
If you use multiple s3 input plugins with one SQS queue, you will face a terrible situation that one input s3 plugin will consume all SQS messages or one input s3 plugin will consume unexpected SQS messages.
