### ISSUE TITLE
Instance profile credentials not working with ECS

### ISSUE THREAD

**Issue by atkinsj** [fluent/fluent-plugin-s3#283]
Using the following deps:

```
Successfully installed jmespath-1.4.0
Successfully installed aws-partitions-1.195.0
Successfully installed aws-eventstream-1.0.3
Successfully installed aws-sigv4-1.1.0
Successfully installed aws-sdk-core-3.61.2
Successfully installed aws-sdk-kms-1.24.0
Successfully installed aws-sdk-s3-1.46.0
Successfully installed aws-sdk-sqs-1.20.0
Successfully installed fluent-plugin-s3-1.1.11
```

and the config:
```
    <instance_profile_credentials>
    </instance_profile_credentials>
```

results in:
```
0 unexpected error error_class=Aws::Errors::MissingCredentialsError error="unable to sign request without credentials set"
```

This configuration worked under EC2. The same IAM role applied to the ECS task results in this error. Are there additional IAM roles or configuration required for ECS?

**Comment by atkinsj** [comment]
Confirmed with:

`curl "http://169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI"`

that I have connectivity and the correct permissions to be able to get temporary tokens from that URI. 

SDK versions look recent enough to have ECSCredentials. Any idea what's going on?

**Comment by atkinsj** [comment]
https://github.com/fluent/fluent-plugin-s3/blob/cbc705141b556bb61452dc801dc23a278188f597/lib/fluent/plugin/out_s3.rb#L437

The switch to use ECSCredentials only appears in `out_s3` and not `in_s3`.

**Comment by repeatedly** [comment]
So this issue for input plugins?

**Comment by atkinsj** [comment]
Yeah. The output plugin correctly uses ECSCredentials or
InstanceProfileCredentials, but the input plugin doesn’t.

**Comment by atkinsj** [comment]
Opened https://github.com/fluent/fluent-plugin-s3/pull/297
