### ISSUE TITLE
How to force flush logs?

### ISSUE THREAD

**Issue by danielzepp** [fluent/fluent-plugin-s3#284]
Hi, i am using kubernetes and fluentd on daemonset (via kops)

I'm worried about losing logs when the node shuts down.

case 1. kops rolling update
case 2. AWS spot instance termination.

How to force flush logs? send something signal?

**Comment by pinge** [comment]
You can easily force flushing the logs to AWS S3:

```bash
sudo kill -USR1 `cat /var/run/td-agent/td-agent.pid`
```

from:
- https://docs.fluentd.org/deployment/signals
- https://support.treasuredata.com/hc/en-us/articles/360000687108-Overview-of-Server-Side-Agent-td-agent-

**Comment by danielzepp** [comment]
@pinge Thanks! resolved 😀
