### ISSUE TITLE
Issue with the date format

### ISSUE THREAD

**Issue by qburst-anoop** [fluent/fluent-plugin-s3#292]
I have two td-agent server one having version 1.2.2 (sender) and another 0.12.40 (receiver). I used to forward the log to both s3 and elastic search. The date format is just fine in elastic search but in S3 file is created to a past date (1970-01-01). Please find the configuration below.

**Sender (1.2.2)**
```
<source>
  @type tail
  path /home/www/app/logs/*-info.log
  pos_file /var/log/td-agent/tmp/info.log.pos
  tag PLATFORM.app
  <parse>
    @type "json"
    time_type string
    localtime true
  </parse>
</source>

<match PLATFORM.*>
  @type forward
  time_as_integer true
  name td-agent-aggregator
  heartbeat_type tcp
  <server>
    host {{ logger_hostname }}
    port 24224
  </server>
  buffer_queue_limit 512
  buffer_chunk_limit 1m
  buffer_type file
  buffer_path /var/log/td-agent/buffer/PLATFORM
  num_threads 2
  flush_interval 5s
</match>
```

**Receiver (0.12.40)**

```
<match PLATFORM.app>
  @type copy
  <store>
    @type s3
    s3_bucket {{ s3_bucket_name_for_log_store }}
    s3_region {{ s3_bucket_region_for_log_store }}
    path logs/app_
    buffer_path /var/log/td-agent/s3/app_
    time_slice_format %Y%m%d%H
    time_slice_wait 10m
    utc
    buffer_chunk_limit 256m
  </store>
  <store>
    @type aws-elasticsearch-service
    reload_connections false
    logstash_prefix PLATFORM.app
    logstash_dateformat %Y.%m.%d
    logstash_format true
    include_tag_key true
    tag_key tag
    buffer_queue_limit 512
    buffer_chunk_limit 8m
    buffer_type file
    buffer_path /var/log/td-agent/buffer/PLATFORM.app
    num_threads 8
    flush_interval 10s
  <endpoint>
    url {{ elastic_search_url }}
    region {{ elastic_search_region }}
  </endpoint>
  </store>
</match>
```

The expected output format in S3 is `app_2019101606_0.gz`  but we are getting `app_1970010100_0.gz`. Please help me to solve this issue.

**Comment by repeatedly** [comment]
> 1970010100_0

This seems time is `nil` or `0` for time slice processing.

```
> Time.at(nil.to_i)
=> 1970-01-01 09:00:00 +0900
```

`out_stdout` also prints similar result?

**Comment by qburst-anoop** [comment]
The same log is writing to elastic search (aws-elasticsearch-service) and everything works as expected there. But the issue is only writing to s3

**Comment by ryanjjung** [comment]
Same here. I have a very similar config that splits logs to S3 and Loggly. The logs come through in Loggly just fine, but in S3, they're dated with absurd timestamps like in the year 1990 and 2056 and dozens of others.

**Comment by repeatedly** [comment]
@ryanjjung So your setup is send data from fluentd v1 to fluentd v0.12?

**Comment by AdamVB** [comment]
I'm running the same output config on a regular VM and also as a Daemonset on Kubernetes. On the Regular VM it works just fine. On Kubernetes it also tags everything with 1970.. not only that but the timekey doesn't work either. Its pretty much spamming the bucket with objects every few seconds:

![image](https://user-images.githubusercontent.com/15871966/68673375-e0ca4c00-0553-11ea-8500-1174f9e51b58.png)


here's the output config:


`  output.conf: |-
    <match **>
      @type copy
      <store>
        @type s3
        aws_key_id "#{ENV['OBS_AK']}" 
        aws_sec_key "#{ENV['OBS_SK']}"
        s3_bucket xxxx
        s3_endpoint https://xxx.com
        s3_region eu-de-01
        path xxxx/ 
        force_path_style true
        time_slice_format %Y%m%d%H%M
        s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
        <buffer tag,time>
          @type file
          path /var/log/fluentd-buffers/s3
          timekey 3600 # 1 hour partition
          timekey_wait 10m
          timekey_use_utc true # use utc
        </buffer>
      </store>
      <store>
        @id elasticsearch 
        @type elasticsearch 
        @log_level "#{ENV['OUTPUT_LOG_LEVEL']}" 
        include_tag_key true 
        host "#{ENV['OUTPUT_HOST']}" 
        port "#{ENV['OUTPUT_PORT']}" 
        path "#{ENV['OUTPUT_PATH']}" 
        scheme "#{ENV['OUTPUT_SCHEME']}" 
        ssl_verify "#{ENV['OUTPUT_SSL_VERIFY']}" 
        ssl_version "#{ENV['OUTPUT_SSL_VERSION']}" 
        type_name "#{ENV['OUTPUT_TYPE_NAME']}" 
        logstash_format true 
        logstash_prefix "#{ENV['LOGSTASH_PREFIX']}" 
        reconnect_on_error true 
        <buffer> 
         @type file 
         path /var/log/fluentd-buffers/kubernetes.system.buffer 
         flush_mode interval 
         retry_type exponential_backoff 
         flush_thread_count 2 
         flush_interval 5s 
         retry_forever 
         retry_max_interval 30 
         chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}" 
         queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}" 
         overflow_action block 
        </buffer>
      </store>
    </match>`


Export to Elasticsearch works just fine. Logs are nicely tagged/parsed and searchable in Kibana with the correct Timestamps.

I'm using this helm chart:

https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch

with the option to install the s3 plugin via fluent-gem.
Tested version 1.1.11 and 1.2.0 so far, same issue.

**Comment by AdamVB** [comment]
Some more interesting info:

when you add `flush_at_shutdown true` to the buffer section and kill the pod it will actually create an object with the correct time:

![image](https://user-images.githubusercontent.com/15871966/68742132-ac0bd280-05ef-11ea-890a-356d3bd454e7.png)

**Comment by repeatedly** [comment]
> when you add flush_at_shutdown true to the buffer section and kill the pod it will actually create an object with the correct time:

That's weird. flush_at_shutdown doesn't affect actual flush processing...

> On the Regular VM it works just fine. On Kubernetes it also tags everything with 1970.. not only that but the timekey doesn't work either.

Is incoming data same between VM and k8s pod?

**Comment by AdamVB** [comment]
I found out the issue, it was indeed something in the input conf. The vm and pod are using different input.

I used this helm chart conf for the pods: 
https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/templates/configmaps.yaml
This one works fine with elasticsearch. 

After a lot of trial and error I found out that this part of the conf breaks the timestamps for s3:

(line 166)
```
    # Fixes json fields in Elasticsearch
    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>

```

When i remove that, the s3 out plugin works fine. Elasticsearch also still works so I just keep that part commented out.

I just started using fluentd, so I'm not quite sure why that part of the config works with elasticsearch but not with the s3 output plugin 🤷‍♂️
