### ISSUE TITLE
S3 Input: excessive memory usage

### ISSUE THREAD

**Issue by TomMizrachi** [fluent/fluent-plugin-s3#294]
When trying to read chunks of data from S3, fluentd memory usage is around 7GB - for an incoming 70MB gzipped log file (700MB after decompressing) in a 5 minutes creation interval.

Is this a known issue? If so is there any solution for it?

In advance this is my configuration file:
```
<source>
    @type s3
    s3_bucket   "#{ENV['CLOUDFLARE_S3_BUCKET']}"
    s3_region   "#{ENV['CLOUDFLARE_S3_REGION']}"
    add_object_metadata true
    store_as gzip
    tag s3.cloudflare
    <sqs>
      queue_name "#{ENV['CLOUDFLARE_SQS_QUEUE']}"
    </sqs>
</source>

<filter s3.cloudflare>
    @type parser
    key_name message
    remove_key_name_field true
    reserve_data yes
    <parse>
        @type json
    </parse>
</filter>

<match s3.cloudflare>
    @type rewrite_tag_filter
    <rule>
        key EdgeRateLimitID
        pattern ^0$
        tag drop_candidate
    </rule>
    <rule>
        key EdgeRateLimitID
        pattern ^0$
        tag s3.cloudflare.ok
        invert true
    </rule>
</match>

<match drop_candidate>
    @type rewrite_tag_filter
    <rule>
        key EdgePathingStatus
        pattern (captchaOk|captchaSucc|captchaNew|captchaFail|captchaErr)
        tag drop
        invert true
    </rule>
    <rule>
        key EdgePathingStatus
        pattern (captchaOk|captchaSucc|captchaNew|captchaFail|captchaErr)
        tag s3.cloudflare.ok
    </rule>
</match>

<match s3.cloudflare.ok>
    @type copy
    <store>
        @type coralogix
        privatekey "#{ENV['CORALOGIX_PRIVATE_KEY']}"
        appname "#{ENV['CORALOGIX_APP_NAME']}"
        subsystemname "new-logs"
        timestamp_key_name EdgeStartTimestamp
        is_json true
    </store>
</match>

<match drop>
    @type null
</match>
```

**Comment by TomMizrachi** [comment]
Also I've noticed that the entire log is being fed into a MultiEventStream object and only afterwards is being emitted to fluentd.
https://github.com/fluent/fluent-plugin-s3/blob/master/lib/fluent/plugin/in_s3.rb#L266-L276

will it help emitting each event separately? or at least be able to control the amount of the events (bulk size)?

**Comment by konstantin-kornienko** [comment]
Same issue for me, after updating to td-agent 3.5.1 (fluent-plugin-s3 1.2.0).
Previous version (td-agent 3.5.0, fluent-plugin-s3 1.1.11) is working fine.

**Comment by ganmacs** [comment]
I'm not sure but how about using file buffer plugin? you can store data to file instead of memory while processing internally.

**Comment by konstantin-kornienko** [comment]
@ganmacs , buffer plugins are for outputs only... We're talking about S3 input (source).

**Comment by ganmacs** [comment]
Right. I know that. I'm suspecting that increasing memory is caused by storing data(from S3 input) on memory buffer because of not using file buffer.

**Comment by konstantin-kornienko** [comment]
Understood. In my case I'm using elasticsearch output and use memory buffer:

Is that you wrote about? Thanks!

```
 <match out.*>
    @type elasticsearch
...
 <buffer>
      @type file
      path /var/tmp/fluentd/elasticsearch_fluentd.buffer
      flush_thread_count 4
      flush_interval 10s

      {# Useful for ASG instances - send full buffer to elastic when terminating -#}
      flush_at_shutdown true

      total_limit_size 750MB
      overflow_action drop_oldest_chunk
      retry_timeout 6h
      retry_forever false
      disable_chunk_backup true
    </buffer>
</match>
```

**Comment by konstantin-kornienko** [comment]
Have died fluentd instance, which tried to process 23 MB gzipped logs file :(
4GB RAM on instance isn't enough for this task  :(

**Comment by bin3377** [comment]
I have exactly same issue when trying to ingest S3 log from cloudflare log push. After tuning the config looks like it finally works on 4G RAM with 1xxM zipped file. The output is not related since it's even got `Worker 0 finished unexpectedly with signal SIGKILL` when using null output. And also tried 1.1.11 version but no help
