### ISSUE TITLE
 issue related to file transfer to separate folder in date wise folder structure in S3 bucket 

### ISSUE THREAD

**Issue by bhaveshmodiatekaplus** [fluent/fluent-plugin-s3#303]
Hi Team,
 I wanted to send my logs to S3 bucket , below is my configuration. 

with below config , it should generate 10MB chunk and flush in every 5 min. 
IN S3 bucket it should create date wise folder and generate file like below.
**Example :**

**apache/access/2019/11/22/access_0.gz**

But with below configuration it is generating thousands of chunk of size 1KB. ideally it should generate 10MB chunk. is there any configuration is missing or am i doing some thing wrong.
please suggest me correct configuration. 

`s3_object_key_format %{path}%{time_slice}access_%{index}.%{file_extension}`
`path apache/access/`                                      
`s3_bucket **my-bucket**`
`time_slice_format %Y/%m/%d`
`<buffer tag,time>`
    ` @type file`
`path C:\Users\bhavesh.modi\Desktop\Log\Fluentd\s3`
`chunk_limit_size 10MB`
`flush_mode interval`
`flush_interval 5m`
`total_limit_size 1024MB`
`flush_at_shutdown true`

**Comment by bit-wrangler** [comment]
Have you ever found a solution to this problem?
