### ISSUE TITLE
Bump aws sdk to support IRSA

### ISSUE THREAD

**Issue by rverma-jm** [fluent/fluent-plugin-s3#312]
Can we bump aws sdk to v2.11.345 to support IRSA base authentication in eks. as mentioned here https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by repeatedly** [comment]
We have already used latest aws-sdk v3. We don't use older and deprecated aws-sdk v2 anymore :)
