### ISSUE TITLE
S3 Access Point support

### ISSUE THREAD

**Issue by csolidum** [fluent/fluent-plugin-s3#313]
It looks like the s3 output plugin doesn't support making requests via S3 access points. 

According to the [access point docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html#access-points-monitoring-logging), you would need make the s3 endpoint  point to `<access_point_name>-<account_id>.s3-accesspoint.<region>.amazonaws.co`. setting the s3_endpoint config option to this i get an exception that `s3_endpoint parameter is not supported for S3, use s3_region instead.` 

Is there a config option to make the S3 plugin use the access point endpoint instead of the generic S3 one? If not, could we allow using the s3_endpoint for this usecase?

**Comment by ganmacs** [comment]
You can use access point docs without s3_endpoint.
Set `s3_bucket` to arn of access point like  `arn:aws:s3:us-west-2:123456789012:accesspoint/prod` in example of https://docs.aws.amazon.com/AmazonS3/latest/dev/using-access-points.html#access-points-monitoring-logging
