### ISSUE TITLE
Force flush is not working.

### ISSUE THREAD

**Issue by saithejareddy** [fluent/fluent-plugin-s3#323]
Hello, 
I am running fluentd as daemonsets in k8s.
I am using SIGUSR1 to force flush the buffer but sometimes its not working and buffer is increasing.
Because of huge buffers, it mag cause effects to other applications running on same node.
I need logs because its very important and at the same, i care for my production applications also.
Is there a way to take care of both?

Thanks in advance.

**Comment by dshackith** [comment]
I am also seeing the same issue. Running `kill -10 1` in the Fluentd pod no longer initiates an immediate flush.

**Comment by saithejareddy** [comment]
> I am also seeing the same issue. Running `kill -10 1` in the Fluentd pod no longer initiates an immediate flush.

Can you try doing this. `kill -USR1 1`
And also setting/increasing [flush_thread_count](https://docs.fluentd.org/deployment/performance-tuning-single-process#use-flush_thread_count-parameter) will help in parallel processing.

**Comment by dshackith** [comment]
This has the same result. No message in logs regarding flush, even in debug. I am using flush_thread_count already, and have added %{uuid_flush} to my s3_object_key_format to ensure no collisions.

**Comment by saithejareddy** [comment]
For me, when i am sending sigterm, it prints force flushing all buffers in logs.
What's your usual buffer's size per pod?
