### ISSUE TITLE
uuid_flush use extra uuidtools gem

### ISSUE THREAD

**Issue by jychen7** [fluent/fluent-plugin-s3#341]
Hi team, 

any idea why not use `SecureRandom.uuid` from stdlib?

https://github.com/fluent/fluent-plugin-s3/blob/eb26edcbf8035be435f31e6f1e149e8ee3ca5256/lib/fluent/plugin/out_s3.rb#L386-L388

https://github.com/fluent/fluent-plugin-s3/blob/eb26edcbf8035be435f31e6f1e149e8ee3ca5256/lib/fluent/plugin/out_s3.rb#L444-L454

**Comment by repeatedly** [comment]
securerandom is introduced since ruby 1.9.3 and uuidtools is widely used before. So I think patch author uses uuidtools.

**Comment by jychen7** [comment]
make senses, shall we replace it now? given the requirement is >= 1.9 already
https://github.com/fluent/fluent-plugin-s3#requirements

**Comment by repeatedly** [comment]
> shall we replace it now?

Yes. I think so. Could you send a patch?

**Comment by jychen7** [comment]
> Yes. I think so. Could you send a patch?

sure, PR is raised and linked with this issue
