### ISSUE TITLE
IRSA multi-region support

### ISSUE THREAD

**Issue by rustysys-dev** [fluent/fluent-plugin-s3#358]
From what I can tell in https://github.com/fluent/fluent-plugin-s3/pull/305 support for IRSA was added.  I tried using it today, and ran into authentication issues.

Looking at the changes in the above mentioned PR it seems that the implementation is locked to us-east-1.   Am I correct in assuming that fluentd cannot use IRSA when in other regions?

If so, I would like to request a fix to support multi-region.

**Comment by repeatedly** [comment]
> I would like to request a fix to support multi-region.

**Comment by rustysys-dev** [comment]
hmm, not sure about the whether the region settings are okay or not but... 
I ended up changing the configuration... I was still using `instance_credentials` but needed to switch to to `web_identity_credentials`.  After switching I was able to connect as expected.

So as I was able to connect,, this seems to be a non-issue... closing (if anyone sees otherwise feel free to reopen)
