### ISSUE TITLE
Support S3-compatible providers (non-AWS)

### ISSUE THREAD

**Issue by mstenta** [fluent/fluent-plugin-s3#383]
### Is your feature request related to a problem? Please describe.

AWS is where S3 started, but other providers offer S3-compatible object storage as well. Examples:

- https://www.linode.com/products/object-storage/
- https://www.digitalocean.com/products/spaces/

It seems that this plugin would work with non-AWS providers, but this statement in the docs leads to uncertainty:

> 
> ### s3_endpoint
> 
> endpoint for S3 compatible services. For example, Riak CS based storage or something. This option is deprecated for AWS S3, use `s3_region` instead.

https://github.com/fluent/fluent-plugin-s3/blob/master/docs/output.md#s3_endpoint

### Describe the solution you'd like

Clarify whether or not non-AWS providers are supported by this plugin, or if that support will be removed in the future.

If the `s3_endpoint` is not going to be removed, then it should not be described as "deprecated" in the documentation.

### Describe alternatives you've considered

None.

**Comment by repeatedly** [comment]
We don't have a plan to remove `s3_endpoint` option.
`This option is deprecated for AWS S3, use s3_region instead.` doesn't say "This option is deprecated"
