### ISSUE TITLE
Tag for published 1.6.1 version is missing

### ISSUE THREAD

**Issue by mindw** [fluent/fluent-plugin-s3#398]
### Describe the bug

The tag for 1.6.1 published some time ago is missing

### To Reproduce

N/A

### Expected behavior

N/A

### Your Environment

```markdown
N/A
```

### Your Configuration

N/A

### Your Error Log

```shell
N/A
```

### Additional context

N/A

**Comment by ashie** [comment]
Hmm, it's weired.
According to commit messages and RubyGems, v1.6.1 is pushed by @kenhys.
And v1.6.1 tag exists in my local repository, so that it should have had ever existed on GitHub.
But it's not present on GitHub for now.
Probably someone delete it mistakenly.

**Comment by ashie** [comment]
I've pushed v1.6.1 tag.
Thank you for your report!
