### ISSUE TITLE
Add Support for x-amz-server-side-encryption

### ISSUE THREAD

**Issue by j-o-s-h** [fluent/fluent-plugin-s3#66]
Add support for the `x-amz-server-side-encryption` header on `PUT` to enable [SSE-S3](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html).

**Comment by repeatedly** [comment]
Could you send a PR?

http://docs.aws.amazon.com/AmazonS3/latest/dev/SSEUsingRubySDK.html

From this document, adding only one option enables SSE.

**Comment by alexanderoot** [comment]
PR submitted here - https://github.com/fluent/fluent-plugin-s3/pull/68
