### ISSUE TITLE
Add support for ${} substitution

### ISSUE THREAD

**Issue by LanceNorskog** [fluent/fluent-plugin-s3#67]
We have set up all of our plugins to use environment variables for configuration items. The s3 plugin does not support this syntax:

aws_api_key #{ENV['AWS_API_KEY']}

**Comment by kiyoto** [comment]
Lance-

Can you try doing

```
aws_api_key '#{ENV['AWS_API_KEY']}"
```

(Note the double quotes)

**Comment by kiyoto** [comment]
Also, I updated the docs's faq > https://github.com/fluent/fluentd-docs/commit/6e5dd3d

**Comment by repeatedly** [comment]
You can use --use-v1-config. This is not fluent-plugin-s3 issue.

**Comment by LanceNorskog** [comment]
Yes, this works:
    aws_api_key "#{ENV['AWS_API_KEY']}"

I have not needed double-quotes in other plugins. I'm using td-agent with --use-v1-config.
(Your example has 3 single quotes and one double. Keyboard-complete is so hard to get right :)

**Comment by repeatedly** [comment]
> I have not needed double-quotes in other plugins

You mean `${}`, not `"#{}"`, right?
`${}` is parsed by plugin itself but `"#{}"` is parsed by fluentd configuration parser.
non-quoted string is for writing string without escape so "" is needed for evaluating Ruby code.

**Comment by LanceNorskog** [comment]
Thanks, that makes sense.
