### ISSUE TITLE
Support for aws-sdk 2.x

### ISSUE THREAD

**Issue by edjames** [fluent/fluent-plugin-s3#69]
Hi

Any plans to add support for the 2.x version of the aws-sdk?

**Comment by repeatedly** [comment]
If someone sends a PR.
I was tired from adapting v2 before: https://github.com/fluent/fluent-plugin-s3/issues/51#issuecomment-59319299

**Comment by edjames** [comment]
Ok, I'll do it when I get some time. Thanks.

**Comment by gerricchaplin** [comment]
Hi guys,
Has anyone had any further time to look into this?
Thanks.

**Comment by edjames** [comment]
Hey, I'm still planning to try this. I've now started a work project using Fluentd and now have the time and motivation to do it. If/when I have a working fork I'll raise a PR.

**Comment by jimwal** [comment]
Hi, Is anyone making any progress on this? Cheers.

**Comment by edjames** [comment]
Hi. It's still on my radar but I'm too busy at work to do this right now.
I cannot commit to doing anything right now unfortunately, so please don't rely on me.

I've also changed my workflow so this is not such a priority for me at this point.
Sorry.
