### ISSUE TITLE
Not flush some of the buffer files when using with in_multiprocess plugin

### ISSUE THREAD

**Issue by ryushu** [fluent/fluent-plugin-s3#71]
I'm using fulent-plugin-s3 with in_multiprocess and my aws instance have 4 core.
One of child process works fine but rest of 4 fluent-plugin-s3 not flush buffers.
Although I am not familiar with this plugin and I dont know if its not only fluent-plugin-s3 issue but in_multiprocess,
Its only happen to fluent-plugin-s3. Other plugin like out_mongo works fine.

This is my environment and config files

##### Environment
OS : Amazon Linux AMI release 2014.09
Instance type : m3.xlarge
Core : 4

td-agent : 1.1.21

###### Input Plugins
in_multiprocess
in_forward

###### Output Plugins
fluent-plugin-forest
out_mongo

###### td-agent.conf
```
<source>
        type multiprocess

        <process>
                cmdline -c /etc/td-agent/td-agent-child-1.conf
        </process>
        <process>
                cmdline -c /etc/td-agent/td-agent-child-2.conf
        </process>
        <process>
                cmdline -c /etc/td-agent/td-agent-child-3.conf
        </process>
        <process>
                cmdline -c /etc/td-agent/td-agent-child-4.conf
        </process>
</source>
```
###### td-agent-child-1.conf
```
# input forward
<source>
        type forward
        port 24224
        bind 0.0.0.0
</source>
```
###### td-agent-child-2.conf
```
# input forward
<source>
        type forward
        port 24225
        bind 0.0.0.0
</source>
```
###### td-agent-child-3.conf
```
# input forward
<source>
        type forward
        port 24226
        bind 0.0.0.0
</source>

include /etc/td-agent/td-agent-common.conf
```
###### td-agent-child-4.conf
```
# input forward
<source>
        type forward
        port 24227
        bind 0.0.0.0
</source>

include /etc/td-agent/td-agent-common.conf
```
td-agent-common.conf
```
<match aaa.bbb.**>
        type copy
        <store>
                type mongo
                buffer_type file
                buffer_path /var/log/td-agent/buffer/
                buffer_chunk_limit 256m
                buffer_queue_limit 128
                flush_interval 60s
                retry_limit 20
                retry_wait 1s

                host *******
                port *******
                database *******
                tag_mapped
                remove_tag_prefix aaa.bbb.
                time_key _time
        </store>
        <store>
                type forest
                subtype s3
                <template>
                        aws_key_id *******
                        aws_sec_key *******
                        s3_bucket *******
                        s3_region *******
                        s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
                        path app_log/${tag_parts[2]}/
                        time_slice_format %Y-%m-%d-%H
                        buffer_path /var/log/td-agent/buffer/s3/${tag_parts[2]}/
                </template>
        </store>

</match>
```
Thanks for helping!

**Comment by repeatedly** [comment]
What does "fluent-plugin-s3 not flush buffers" mean?
Send USR1 signal but not flush? or passes 1 hour but not flush?

BTW, td-agent-child-1.conf and td-agent-child-2.conf have only input plugin configuration.
It doesn't process received logs.

And you should not use same buffer_path between fluentd instances. It may cause race condition.

**Comment by ryushu** [comment]
>What does "fluent-plugin-s3 not flush buffers" mean?
>Send USR1 signal but not flush? or passes 1 hour but not flush?

"fluent-plugin-s3 not flush buffers" mean passes 1 hour but not fush.

>BTW, td-agent-child-1.conf and td-agent-child-2.conf have only input plugin configuration.
>It doesn't process received logs.

Its just mistake. 
In fact td-agent-child-1.conf and td-agent-child-2.conf also have include path.
Sorry about that.

>And you should not use same buffer_path between fluentd instances. It may cause race condition

I will try the separate buffer_path and report it.

**Comment by repeatedly** [comment]
To separate the problem, test plugin without in_multiprocess is better.

**Comment by ryushu** [comment]
Setting different buffer_path of each child process works fine so far.
Thanks for helping !

**Comment by repeatedly** [comment]
Good to hear!
