### ISSUE TITLE
s3 input plugin?

### ISSUE THREAD

**Issue by ajohnstone** [fluent/fluent-plugin-s3#72]
Is there any intention to also consume the logs that that this writes as an input plugin?

**Comment by repeatedly** [comment]
Currently, there is no input plugin plan because user-case seems rare.
If someone write good plugin, I can adopt it.

**Comment by okkez** [comment]
@ajohnstone  I'm trying to implement input plugin #105 
If you want this input plugin, you can try #105 and comment, please.

**Comment by ofirnn** [comment]
Hey,
Any news regards fluent-s3-input? besides the pull request?

**Comment by Bizzelicious** [comment]
@ofirnn Input released 14 days ago https://github.com/fluent/fluent-plugin-s3/blob/master/README.md#input-setup

**Comment by repeatedly** [comment]
I have already released new version including input plugin. closed.
