### ISSUE TITLE
Check if logs are sent to s3

### ISSUE THREAD

**Issue by papiveron** [fluent/fluent-plugin-s3#78]
Hi,

Please can some one tell me how to check if fluentd is really sending logs to s3? Is this done once fluentd receives input logs like for ES and file type?
What is the interval for fluentd to send log to s3? At minight? Instantly?

Here is my configuration :

		<match nginx.api1.mydomain.error.*>
		    type copy   
		    <store>
			type file
			path /var/log/td-agent/nginx-api1.mydomain-error.log
		    </store>
		    <store>
			type elasticsearch
			hosts es_ip_address
			logstash_format true
			include_tag_key true
			tag_key _key
			flush_interval 10s
		    </store>
		    <store>
			type s3
			s3_bucket s3.yyy.extra.websites.eu-west-1.xxx
			s3_region eu-west-1
			s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
			path logs/
			buffer_path /var/log/td-agent/nginx-api1.mydomain-error-s3.log 
			time_slice_format %Y%m%d-%H
			time_slice_wait 10m
			utc
		    </store>
		</match>

Thanks

**Comment by repeatedly** [comment]
> Is this done once fluentd receives input logs like for ES and file type?
> What is the interval for fluentd to send log to s3? At minight? Instantly?

This is described by documents.
See below:

http://docs.fluentd.org/articles/out_s3
http://docs.fluentd.org/articles/buffer-plugin-overview#time-sliced-plugin-overview

**Comment by papiveron** [comment]
Thank you,

It's working. I'll do further reads to understand fine how the slice works.

Regards.
