### ISSUE TITLE
Split S3 files by date

### ISSUE THREAD

**Issue by edjames** [fluent/fluent-plugin-s3#84]
Hi

Is it possible to split S3 logfiles by date?

I want each S3 logfile to only contain events that occur during a specified time period (e.g. the same day). This would make it very easy to grab all my data for a specific day for processing (or re-processing).

Thanks,
Ed.

**Comment by edjames** [comment]
Further to this, I have read the docs here: http://docs.fluentd.org/articles/out_s3

I need to know how accurate this time-slicing is and whether I can rely on a time-slice no not cross the date line between calendar days. Under heavy load is this accurate and reliable?

**Comment by repeatedly** [comment]
> I need to know how accurate this time-slicing is and whether I can rely on a time-slice no not cross the date line between calendar days. Under heavy load is this accurate and reliable?

Time slice is based on event time.
On `time_slice_format %Y%m%d`, "Tues, June 15 2015" time event is stored into "20150615".
So it should not be immune to heavy load.

**Comment by edjames** [comment]
So if I understand this correctly, if I'm time-slicing by day, then an event are you saying 2 events from different days will never be in the same log file i.e. every log file will contain events only from the same day?

Also, could you explain what you mean by this: `So it should not be immune to heavy load.`

Many thanks.

**Comment by repeatedly** [comment]
> if I'm time-slicing by day, then are you saying 2 events from different days will never be in the same log file

Exactly.

> Also, could you explain what you mean by this: 

I assume you worry about the system generates wrong timestamp and fluentd uses it on heavy load environment.

**Comment by edjames** [comment]
That's great, thanks.
