### ISSUE TITLE
Insert time variable in the s3_object_key_format

### ISSUE THREAD

**Issue by papiveron** [fluent/fluent-plugin-s3#89]
Hi,

Please, is there a **time** variable for **s3_object_key_format**?
I would to get log in my bucket in folder per **year**,; **month**, **day_of_month**, and a file name containing the **time** and file extension. This is my configuration :

```
<match my_tag>
        type s3
        s3_bucket my_bucket
        s3_region eu-west-1
        #s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
        s3_object_key_format %{path}%{time_slice}/stats_log-%{time}_%{index}.%{file_extension}
        path logs/
        buffer_path /var/log/td-agent/buffer_file.log
        time_slice_format %Y/%m/%d
        time_format %H:%M:%S
        time_slice_wait 10m
        utc
</match>
```

As you can see above, I added forward slashes (**"/"**) between the time silice format field, to separate them in directories. But is like the **%{time}** variable I put there doesn't exist and as result this field is empty in my log file. 
Please how can I achieve this? 

Thank you. 

Best regards,

**Comment by papiveron** [comment]
This is exactly what I want as result for example:

```
 https://console.aws.amazon.com/s3/home?region=eu-west-1#&bucket=my_bucket&prefix=logs/2015/07/30/
```

And then a file inside generated to day will have this name :
```
stats_logs-10:50:36_0.gz
```

Thanks again for helping.

**Comment by repeatedly** [comment]
No way. If you want to generate such specific path,
extending s3 plugin is better.

**Comment by papiveron** [comment]
Hi   @repeatedly I don't understand what you mean by extending s3 plugin please. Can you be more clear? Do you mean modify the code source?

Thanks

**Comment by repeatedly** [comment]
> Do you mean modify the code source?

No. Writing new plugin based on S3Output.

http://docs.fluentd.org/articles/plugin-development
http://docs.fluentd.org/articles/plugin-management

**Comment by papiveron** [comment]
Ok,

I will  have a look at this. But it means I have to use the s3Ouput plugin for development.

THANKS

**Comment by papiveron** [comment]
@repeatedly, I saw you close the ticket.

But please instead of writing my own plugin, Do you thing I can play on the **time_sliced_format** variable to have something just like **2015/07/30** ? If so how can I achieve this? How can I escape the forward slashes? Because **%Y/%m/%d** doesn't work, I don't know if I can use backward slashes (**%Y\/%m\/%d**).

Best regards.

**Comment by repeatedly** [comment]
What does ` %Y/%m/%d doesn't work` mean?
It seems work.

```aconf
% RUBYLIB=~/dev/fluentd/fluentd/lib:~/dev/fluentd/fluent-plugin-s3/lib fluentd -c s3.conf                         (git)-[master]
2015-07-30 23:40:30 +0900 [info]: reading config file path="s3.conf"
2015-07-30 23:40:30 +0900 [info]: starting fluentd-0.12.15
2015-07-30 23:40:30 +0900 [info]: gem 'fluent-mixin-config-placeholders' version '0.3.0'
2015-07-30 23:40:30 +0900 [info]: gem 'fluent-plugin-s3' version '0.5.10'
2015-07-30 23:40:30 +0900 [info]: gem 'fluent-plugin-secure-forward' version '0.3.2'
2015-07-30 23:40:30 +0900 [info]: gem 'fluent-plugin-td' version '0.10.27'
2015-07-30 23:40:30 +0900 [info]: gem 'fluent-plugin-td-monitoring' version '0.2.0'
2015-07-30 23:40:30 +0900 [info]: gem 'fluentd' version '0.12.12'
2015-07-30 23:40:30 +0900 [info]: adding match pattern="s3.**" type="s3"
2015-07-30 23:40:31 +0900 [info]: adding source type="forward"
2015-07-30 23:40:31 +0900 [info]: using configuration file: <ROOT>
  <source>
    type forward
  </source>
  <match s3.**>
    type s3
    aws_key_id xxxxxx
    aws_sec_key xxxxxx
    s3_bucket fluent-plugin-s3
    path test
    buffer_type memory
    flush_interval 5s
    buffer_chunk_limit 256m
    time_slice_format %Y/%m/%d
    flush_at_shutdown true
  </match>
</ROOT>
2015-07-30 23:40:34 +0900 [info]: listening fluent socket on 0.0.0.0:24224
```

![s3 result](http://i.gyazo.com/4eb836dfae17105b5d35d01d803f1a35.png)

**Comment by papiveron** [comment]
Ah that's good,

Maybe I didn't wait enough as logs are buffered before being send to s3. In fact I don't see my logs in s3 while seeing them in buffer file, and thought it was not working.

At the fluentd client/forwarder side, there is a **flush_interval** variable. How can I test my plugin is outputing I expected at the server side please? Thanks.

Thank you for your screenshot example. I will put bag my configuration.

Regards.

**Comment by papiveron** [comment]
Sorry,

I saw there is a **flush_interval** in s3 plugin parameter too. Apologises, Let me try on my way.

Regards.

**Comment by papiveron** [comment]
It Works with this s3_object_key_format value :

```
 s3_object_key_format %{path}%{time_slice}/stats_log-%H:%M:%S_%{index}.%{file_extension}
```
The only issue now is that my log file has the name : **stats_log-%H:%M:%S_0.gz**

I'm trying to see how to substitute time variable.

Regards.

**Comment by papiveron** [comment]
I got it !!!!

This i what I did :
```
s3_object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
time_slice_format %Y/%m/%d/stats_log-%H:%M:%S
```

And it works !!!

Hope it could someone else.

Thanks a lot @repeatedly 

Regards.

**Comment by repeatedly** [comment]
Ah, I didn't come up with this idea.

Note that fluentd's TimeSlicedOutput, S3 plugin uses it, separates buffers by time_slice_format.
In this configuration, fluentd creates lots of buffer because `time_slice_format` has `%S`.
So memory usage or IO cost may be increased but I assume this is not problem on non high-loaded environment.

**Comment by papiveron** [comment]
Ah thank you,

I will remove seconds in **time_slice_format**, this is a good information to know.

Is there a sort of fluentd best practices book or something like that?

Thanks.

Regards,
