### ISSUE TITLE
aws-sdk version 2 support?

### ISSUE THREAD

**Issue by edjames** [fluent/fluent-plugin-s3#93]
Hi

Are you planning on upgrading the gem to support version 2 of the aws-sdk?

Thanks,
Ed.

**Comment by repeatedly** [comment]
We need testers: https://github.com/fluent/fluent-plugin-s3/pull/85

**Comment by repeatedly** [comment]
I release 0.6.0.pre1 which uses AWS SDK v2.
We need testers but this issue is resolved.

**Comment by edjames** [comment]
Great, thanks.
