### ISSUE TITLE
s3_object_key_format variable assigments

### ISSUE THREAD

**Issue by Viktor86** [fluent/fluent-plugin-s3#94]
Hi,

want to create logs like
path/current_date/current_time.gz  with every hour file creation

we have time_slice, but what I need to set on current_date ?
s3_object_key_format %{path}/%current_date/%{time_slice}.%{file_extension}

time_slice_format %Y%m%d-%H

please help

**Comment by repeatedly** [comment]
No straightforward way. See: https://github.com/fluent/fluent-plugin-s3/issues/89
or use `uuid_flush` if you want to guarantee unique file.

**Comment by repeatedly** [comment]
Close. see previous comment.
