### ISSUE TITLE
REQ: Object expiry

### ISSUE THREAD

**Issue by Yanson** [fluent/fluent-plugin-s3#95]
I would like to be able to set an expiry time / TTL on the files uploaded to S3.

This should be a straightforward passthrough of a config like is done for reduced_redundancy.

Thanks.

**Comment by repeatedly** [comment]
Could you send a patch?
If not, could you point ruby reference here?

**Comment by Yanson** [comment]
I've looked into this but it seems I've misinterpreted the docs. The 'expires' setting is for caching not TTL: http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html

It would be possible to add a TTL which is managed by the bucket lifecycle, but I think that is beyond the scope of this plugin.
http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/BucketLifecycle.html

Cheers.

**Comment by repeatedly** [comment]
I see. Close this issue.
